//! Rust code generation for script modules.
//!
//! [`generate`] turns a verified [`Module`] into Rust source. The generated
//! code is the instruction dispatch of the interpreter, compiled: one
//! `step_<n>` function per module function, with the module's jumps and
//! branches as Rust control flow and every operation calling the shared
//! [`pulsar_script_vm::exec`] functions. It implements
//! [`CompiledCode`](pulsar_script_vm::compiled::CompiledCode) and links
//! through [`Program::link_compiled`](pulsar_script_vm::Program::link_compiled),
//! so it runs on the same VM as an interpreted module: the same instances
//! and per-instance variables, the same natives and capability checks, the
//! same call stack, call-depth limit, instruction budget, waiting and error
//! traces. Nothing about those is re-implemented here, which is what keeps
//! the two backends from diverging; `pulsar_script_conformance` runs both on
//! the same modules and compares everything observable.
//!
//! The generated source defines:
//!
//! - `pub fn module() -> Module`: the module without its instruction
//!   streams (imports, constants, variables, signatures, events and debug
//!   info stay);
//! - `pub fn link(registry, events, policy) -> Result<Program, LinkError>`.
//!
//! Generation verifies the module first, so generated code never has to.

pub mod actor;

use std::fmt::Write as _;

use pulsar_script_vm::{verify, BinOp, CollOp, Instr, Module, Reg, Type, UnOp, VerifyError};

/// Why a module could not be turned into Rust.
#[derive(Debug)]
pub enum CodegenError {
    /// The module did not verify. Generated code relies on verification, so
    /// nothing is generated for a module that fails it.
    Verify(VerifyError),
}

impl std::fmt::Display for CodegenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Verify(error) => write!(f, "the module does not verify: {error}"),
        }
    }
}

impl std::error::Error for CodegenError {}

impl From<VerifyError> for CodegenError {
    fn from(error: VerifyError) -> Self {
        Self::Verify(error)
    }
}

/// How generated code names things outside itself.
#[derive(Clone, Debug)]
pub struct Options {
    /// The path under which generated code finds `pulsar_script_vm`: that
    /// crate's name where it is a direct dependency, or a re-export (a game
    /// reaches it through `pulsar_game`).
    pub vm_crate: String,
}

impl Default for Options {
    fn default() -> Self {
        Self { vm_crate: "pulsar_script_vm".to_owned() }
    }
}

/// Generate Rust for `module` with default [`Options`]. See the crate docs.
pub fn generate(module: &Module) -> Result<String, CodegenError> {
    generate_with(module, &Options::default())
}

/// Generate Rust for `module`. See the crate docs.
pub fn generate_with(module: &Module, options: &Options) -> Result<String, CodegenError> {
    verify(module)?;

    let mut stripped = module.clone();
    for function in &mut stripped.functions {
        function.code.clear();
    }
    let meta = stripped.to_json().expect("modules serialize");
    let fence = "#".repeat(longest_hash_run(&meta) + 1);

    let mut out = String::new();
    let _ = writeln!(out, "// @generated by pulsar_script_codegen from script module `{}`. Do not edit.", module.name);
    out.push_str(&prelude(&options.vm_crate));
    let _ = writeln!(out, "const MODULE: &str = r{fence}\"{meta}\"{fence};\n");
    out.push_str(MODULE_FNS);

    out.push_str("struct Code;\n\nimpl CompiledCode for Code {\n");
    out.push_str("    fn step(&self, func: u32, pc: &mut usize, r: &mut [Value], cx: &mut Cx<'_, '_>) -> Result<Exit, ScriptErrorKind> {\n");
    out.push_str("        match func {\n");
    for index in 0..module.functions.len() {
        let _ = writeln!(out, "            {index} => step_{index}(pc, r, cx),");
    }
    out.push_str("            _ => unreachable!(\"function index out of range\"),\n        }\n    }\n}\n");

    for (index, function) in module.functions.iter().enumerate() {
        let _ = writeln!(out, "\n/// `{}`", function.name);
        out.push_str("#[allow(unused_variables, unused_mut, unreachable_code, clippy::all)]\n");
        let _ = writeln!(
            out,
            "fn step_{index}(pc: &mut usize, r: &mut [Value], cx: &mut Cx<'_, '_>) -> Result<Exit, ScriptErrorKind> {{"
        );
        out.push_str("    loop {\n        match *pc {\n");
        for (pc, instr) in function.code.iter().enumerate() {
            let _ = writeln!(out, "            {pc} => {{");
            out.push_str("                cx.spend()?;\n");
            emit(&mut out, module, instr, pc);
            out.push_str("            }\n");
        }
        out.push_str("            _ => unreachable!(\"pc out of range\"),\n        }\n    }\n}\n");
    }
    Ok(out)
}

fn prelude(vm: &str) -> String {
    format!(
        "\
use std::sync::Arc;

use {vm}::compiled::{{CompiledCode, Cx, Exit}};
use {vm}::exec;
use {vm}::{{
    BinOp, CapabilityPolicy, CollOp, EventCatalog, LinkError, Module, NativeRegistry, Program, ScriptErrorKind, Type, UnOp, Value,
}};

"
    )
}

const MODULE_FNS: &str = "\
/// The module without its instruction streams.
pub fn module() -> Module {
    Module::from_json(MODULE).expect(\"generated module data is valid\")
}

/// Link the generated code against `registry`, as `Program::link_with_policy`
/// links an interpreted module.
pub fn link(
    registry: &NativeRegistry,
    events: Option<&dyn EventCatalog>,
    policy: &CapabilityPolicy,
) -> Result<Program, LinkError> {
    Program::link_compiled(Arc::new(module()), Arc::new(Code), registry, events, policy)
}

";

fn longest_hash_run(text: &str) -> usize {
    let mut longest = 0;
    let mut run = 0;
    for c in text.chars() {
        if c == '#' {
            run += 1;
            longest = longest.max(run);
        } else {
            run = 0;
        }
    }
    longest
}

fn reg(r: Reg) -> String {
    format!("r[{r}]")
}

fn binop(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "Add",
        BinOp::Sub => "Sub",
        BinOp::Mul => "Mul",
        BinOp::Div => "Div",
        BinOp::Rem => "Rem",
        BinOp::Eq => "Eq",
        BinOp::Ne => "Ne",
        BinOp::Lt => "Lt",
        BinOp::Le => "Le",
        BinOp::Gt => "Gt",
        BinOp::Ge => "Ge",
        BinOp::And => "And",
        BinOp::Or => "Or",
    }
}

fn unop(op: UnOp) -> &'static str {
    match op {
        UnOp::Neg => "Neg",
        UnOp::Not => "Not",
        UnOp::IntToFloat => "IntToFloat",
        UnOp::FloatToInt => "FloatToInt",
        UnOp::ToStr => "ToStr",
    }
}

/// A Rust expression building `ty`.
fn type_expr(ty: &Type) -> String {
    match ty {
        Type::Unit => "Type::Unit".into(),
        Type::Bool => "Type::Bool".into(),
        Type::Int => "Type::Int".into(),
        Type::Float => "Type::Float".into(),
        Type::Str => "Type::Str".into(),
        Type::Entity => "Type::Entity".into(),
        Type::Component(name) => format!("Type::Component({name:?}.to_owned())"),
        Type::Object(name) => format!("Type::Object({name:?}.to_owned())"),
        Type::List(element) => format!("Type::List(Box::new({}))", type_expr(element)),
        Type::Map(key, value) => format!("Type::Map(Box::new({}), Box::new({}))", type_expr(key), type_expr(value)),
        Type::Tuple(items) => format!("Type::Tuple(vec![{}])", items.iter().map(type_expr).collect::<Vec<_>>().join(", ")),
    }
}

fn emit(out: &mut String, module: &Module, instr: &Instr, pc: usize) {
    let next = pc + 1;
    let advance = |out: &mut String| {
        let _ = writeln!(out, "                *pc = {next};");
    };
    match instr {
        Instr::Const { dst, index } => {
            let _ = writeln!(out, "                {} = cx.constants[{index}].clone();", reg(*dst));
            advance(out);
        }
        Instr::Move { dst, src } => {
            let _ = writeln!(out, "                {} = {}.clone();", reg(*dst), reg(*src));
            advance(out);
        }
        Instr::Unary { op, dst, src } => {
            let _ = writeln!(
                out,
                "                {} = exec::unary(UnOp::{}, &{}, cx.checked)?;",
                reg(*dst),
                unop(*op),
                reg(*src)
            );
            advance(out);
        }
        Instr::Binary { op, dst, a, b } => {
            let _ = writeln!(
                out,
                "                {} = exec::binary(BinOp::{}, &{}, &{}, cx.checked)?;",
                reg(*dst),
                binop(*op),
                reg(*a),
                reg(*b)
            );
            advance(out);
        }
        Instr::Jump { target } => {
            let _ = writeln!(out, "                *pc = {target};");
        }
        Instr::Branch { cond, then, otherwise } => {
            let _ = writeln!(
                out,
                "                *pc = if matches!({}, Value::Bool(true)) {{ {then} }} else {{ {otherwise} }};",
                reg(*cond)
            );
        }
        Instr::Call { func, args, dst } => {
            let args = args.iter().map(|a| format!("{}.clone()", reg(*a))).collect::<Vec<_>>().join(", ");
            let dst = dst.map_or("None".to_owned(), |d| format!("Some({d})"));
            // The caller stays at the call site; the VM moves it on when the
            // callee returns.
            let _ = writeln!(out, "                return Ok(Exit::Call {{ func: {func}, args: vec![{args}], dst: {dst} }});");
        }
        Instr::CallNative { import, args, dst } => {
            let sig = &module.imports[*import as usize].sig;
            out.push_str("                let mut values = std::mem::take(&mut *cx.scratch);\n");
            out.push_str("                values.clear();\n");
            for a in args {
                let _ = writeln!(out, "                values.push({}.clone());", reg(*a));
            }
            let _ = writeln!(
                out,
                "                let result = exec::call_native(&cx.natives[{import}], &mut *cx.host, &mut values);"
            );
            out.push_str("                let result = match result {\n");
            out.push_str("                    Ok(value) => value,\n");
            out.push_str("                    Err(kind) => {\n                        *cx.scratch = values;\n                        return Err(kind);\n                    }\n                };\n");
            // `inout` arguments are written back to the caller's registers.
            for (index, (param, arg)) in sig.params.iter().zip(args).enumerate() {
                if param.inout {
                    let _ = writeln!(
                        out,
                        "                if values[{index}].fits(&{}) {{ {} = values[{index}].clone(); }}",
                        type_expr(&param.ty),
                        reg(*arg)
                    );
                }
            }
            out.push_str("                *cx.scratch = values;\n");
            if let Some(dst) = dst {
                let _ = writeln!(out, "                {} = result;", reg(*dst));
            }
            advance(out);
            // A latent native asked for the call to suspend; `*pc` is already past it.
            out.push_str("                if exec::latent_requested(&*cx.host) {
                    return Ok(Exit::Wait(0.0));
                }
");
        }
        Instr::LoadVar { dst, var } => {
            let _ = writeln!(out, "                {} = cx.vars[{var}].clone();", reg(*dst));
            advance(out);
        }
        Instr::StoreVar { var, src } => {
            let _ = writeln!(out, "                cx.vars[{var}] = {}.clone();", reg(*src));
            advance(out);
        }
        Instr::SelfEntity { dst } => {
            let _ = writeln!(out, "                {} = Value::Entity(cx.host.entity);", reg(*dst));
            advance(out);
        }
        Instr::Now { dst } => {
            let _ = writeln!(out, "                {} = Value::Float(cx.host.time);", reg(*dst));
            advance(out);
        }
        Instr::Wait { seconds } => {
            let _ = writeln!(out, "                let seconds = {}.as_float().unwrap_or(0.0);", reg(*seconds));
            out.push_str("                // NaN and negative waits resume on the next opportunity.\n");
            out.push_str("                let seconds = if seconds > 0.0 { seconds } else { 0.0 };\n");
            advance(out);
            out.push_str("                return Ok(Exit::Wait(seconds));\n");
        }
        Instr::Collection { op, dst, args } => {
            // As in the interpreter: a result written over its own first
            // argument moves it, so the edit happens in place.
            let operands = args
                .iter()
                .enumerate()
                .map(|(position, a)| {
                    if position == 0 && a == dst && !args[1..].contains(a) {
                        format!("std::mem::replace(&mut {}, Value::Unit)", reg(*a))
                    } else {
                        format!("{}.clone()", reg(*a))
                    }
                })
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(out, "                {} = exec::collection(CollOp::{op:?}, &mut [{operands}])?;", reg(*dst));
            advance(out);
        }
        Instr::Return { value } => {
            let value = value.map_or("Value::Unit".to_owned(), |v| format!("{}.clone()", reg(v)));
            let _ = writeln!(out, "                return Ok(Exit::Return({value}));");
        }
    }
}
