use std::path::Path;

use engine_fs::virtual_fs;
use engine_state::{register_default_settings, ProjectSettings};

use super::native_scripts::{discover_script_crates, ScriptCrate};

/// Helio revision selected by the Pulsar workspace.
///
/// The build script derives this from `[workspace.dependencies]` and rejects
/// mismatched Helio package revisions. Generated games use the same revision
/// so their direct Helio values remain compatible with Pulsar's public API.
pub const HELIO_GIT_REVISION: &str = env!("PULSAR_HELIO_GIT_REVISION");

/// The generated game's `[dependencies]` + `[patch."…"]` blocks, baked from this
/// engine build's own workspace manifest by `engine_backend/build.rs`.
///
/// Emitting these verbatim makes every generated project resolve the *exact*
/// crate versions and sources this engine uses — path deps point at the engine
/// checkout, git deps carry their pinned revs, and the full `[patch]` table
/// unifies the Pulsar ecosystem to single local copies. This is what keeps a
/// Play-In-Editor game ABI-compatible with the editor it loads into (shared
/// `wgpu` device across the dylib boundary) and fixes the version skew that a
/// bare `git = "…Pulsar-Native"` dependency otherwise produces.
const GAME_MANIFEST_DEPS: &str =
    include_str!(concat!(env!("OUT_DIR"), "/game_manifest_deps.toml"));

fn settings_string(
    settings: Option<&ProjectSettings>,
    owner: &str,
    key: &str,
    default: &str,
) -> String {
    settings
        .and_then(|s| s.get(owner, key))
        .and_then(|v| v.as_str().ok().map(str::to_string))
        .unwrap_or_else(|| default.to_string())
}

fn settings_bool(
    settings: Option<&ProjectSettings>,
    owner: &str,
    key: &str,
    default: bool,
) -> bool {
    settings
        .and_then(|s| s.get(owner, key))
        .and_then(|v| v.as_bool().ok())
        .unwrap_or(default)
}

fn cargo_safe_name(raw: &str) -> String {
    let lowered = raw.trim().to_ascii_lowercase();
    let mut out = String::with_capacity(lowered.len());
    for ch in lowered.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' || ch == '-' {
            out.push(ch);
        } else if ch.is_whitespace() {
            out.push('_');
        }
    }
    let out = out.trim_matches('_').to_string();
    if out.is_empty() {
        "pulsar_project".to_string()
    } else {
        out
    }
}

fn ensure_core_cargo_toml(project_root: &Path) -> Result<(), String> {
    // Register schemas once before any project settings reads.
    register_default_settings();

    let settings = ProjectSettings::new(project_root);
    if let Some(ref s) = settings {
        s.load_all();
    }

    let fallback_name = project_root
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("pulsar_project")
        .to_string();

    let project_name = settings_string(settings.as_ref(), "project", "name", &fallback_name);
    let crate_name = cargo_safe_name(&project_name);
    let version = settings_string(settings.as_ref(), "project", "version", "0.1.0");
    let description = settings_string(settings.as_ref(), "project", "description", "");
    let author = settings_string(settings.as_ref(), "project", "author", "");
    let license_spdx = settings_string(settings.as_ref(), "project", "license_spdx", "");
    let license = settings_string(settings.as_ref(), "project", "license", "MIT");
    let optimize = settings_bool(settings.as_ref(), "build", "optimize", false);
    let debug_symbols = settings_bool(settings.as_ref(), "build", "debug_symbols", true);

    let selected_license = if license_spdx.is_empty() {
        license
    } else {
        license_spdx
    };

    // Gameplay script crates (#653): every `scripts/*` crate becomes a path
    // dependency of the game, so one build compiles user gameplay code into
    // the same dylib the editor embeds.
    let script_crates = discover_script_crates(project_root);

    let cargo_toml_path = project_root.join("Cargo.toml");
    let should_write_cargo = if cargo_toml_path.exists() {
        let existing = String::from_utf8(
            virtual_fs::read_file(&cargo_toml_path)
                .map_err(|e| format!("Failed to read existing Cargo.toml: {e}"))?,
        )
        .map_err(|e| format!("Failed to read existing Cargo.toml as UTF-8: {e}"))?;

        existing.contains("Generated Pulsar game project:")
            || existing.contains("Generated by Pulsar Core Project Builder")
    } else {
        true
    };

    if !should_write_cargo {
        return Ok(());
    }

    let mut package_lines = vec![
        "# Generated by Pulsar Core Project Builder.".to_string(),
        "[package]".to_string(),
        format!("name = \"{}\"", crate_name),
        format!("version = \"{}\"", version),
        "edition = \"2021\"".to_string(),
        "publish = false".to_string(),
    ];

    if !description.is_empty() {
        package_lines.push(format!(
            "description = \"{}\"",
            description.replace('"', "\\\"")
        ));
    }
    if !author.is_empty() {
        package_lines.push(format!("authors = [\"{}\"]", author.replace('"', "\\\"")));
    }
    if !selected_license.is_empty() {
        package_lines.push(format!(
            "license = \"{}\"",
            selected_license.replace('"', "\\\"")
        ));
    }

    let profile_opt = if optimize { 3 } else { 0 };
    let profile_debug = if debug_symbols { 2 } else { 0 };

    // A `[lib]` `cdylib` target is emitted alongside the default binary so the
    // editor can build the project as a dynamic library and embed it for
    // Play-In-Editor (issue #243). `rlib` is kept so anything that wants to
    // link the project as a normal Rust lib still can. `src/lib.rs` (generated below)
    // exports the `pulsar_pie_*` C-ABI symbols the editor loads.
    //
    // The `[dependencies]` + `[patch]` blocks come from `GAME_MANIFEST_DEPS`,
    // baked from the engine's own workspace at build time so the game resolves
    // the exact same crate versions/sources as the editor. Script-crate path
    // deps are spliced into that `[dependencies]` table (before its first
    // `[patch.*]` table) because TOML forbids reopening a table.
    let cargo_content = format!(
        "{package}\n\n[lib]\ncrate-type = [\"cdylib\", \"rlib\"]\n\n\
{deps}\n[profile.dev]\nopt-level = {opt}\ndebug = {debug}\n{workspace_block}",
        package = package_lines.join("\n"),
        deps = splice_script_dependencies(GAME_MANIFEST_DEPS, &script_crates),
        opt = profile_opt,
        debug = profile_debug,
        workspace_block = workspace_block(&script_crates),
    );

    virtual_fs::write_file(&cargo_toml_path, cargo_content.as_bytes())
        .map_err(|e| format!("Failed to write Cargo.toml: {e}"))?;

    Ok(())
}

/// Ensure the core project bootstrap files exist and are up to date.
///
/// This is engine-owned project wiring. PBGC should only emit class files.
pub fn ensure_core_bootstrap(project_root: &Path) -> Result<(), String> {
    // ── scripts/ — user gameplay script crates (#653) ────────────────────────
    // Must run BEFORE manifest/engine_main generation so both can wire it.
    ensure_scripts_crate(project_root)?;

    ensure_core_cargo_toml(project_root)?;

    let src_dir = project_root.join("src");
    virtual_fs::create_dir_all(&src_dir)
        .map_err(|e| format!("Failed to create src directory: {e}"))?;

    let classes_dir = src_dir.join("classes");
    virtual_fs::create_dir_all(&classes_dir)
        .map_err(|e| format!("Failed to create classes directory: {e}"))?;

    // Always regenerate classes/mod.rs from what's actually on disk.
    // This removes stale `pub mod Foo;` lines for deleted/renamed classes.
    let classes_mod = classes_dir.join("mod.rs");
    {
        let mut mod_content = "//! Auto-generated by Pulsar Core Project Builder.\n\
             //! DO NOT EDIT MANUALLY - YOUR CHANGES WILL BE OVERWRITTEN\n\n"
            .to_string();

        // Emit a `pub mod` declaration for every subdirectory that has a mod.rs.
        if let Ok(entries) = virtual_fs::list_dir(&classes_dir) {
            let mut names: Vec<String> = entries
                .into_iter()
                .filter(|e| e.is_dir)
                .filter(|e| {
                    let mod_rs_path = classes_dir.join(&e.name).join("mod.rs");
                    mod_rs_path.exists()
                })
                .map(|e| e.name.clone())
                .collect();
            names.sort();
            for name in names {
                mod_content.push_str(&format!("pub mod {};\n", name));
            }
        }

        virtual_fs::write_file(&classes_mod, mod_content.as_bytes())
            .map_err(|e| format!("Failed to write classes/mod.rs: {e}"))?;
    }

    // Always regenerate main.rs — the editor and JSON are the source of truth.
    let main_rs = src_dir.join("main.rs");
    {
        let project_name = project_root
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("pulsar_project");

        let main_content = format!(
            r#"//! {project_name} — generated by Pulsar Core Project Builder.

use pulsar_game::prelude::*;
use winit::event_loop::EventLoop;

mod classes;
mod engine_main;

fn main() {{
    tracing_subscriber::fmt()
        .with_env_filter(std::env::var("RUST_LOG").unwrap_or_else(|_| "info".into()))
        .init();

    tracing::info!("Starting {{}}", env!("CARGO_PKG_NAME"));

    let threads = std::thread::available_parallelism()
        .map(|n| n.get())
        .unwrap_or(4);

    let mut game = TickLoop::new(TickMode::default(), threads);

    if let Err(e) = engine_main::setup(&mut game) {{
        tracing::error!("Level setup failed: {{e}}");
        std::process::exit(1);
    }}

    tracing::info!("World ready — opening primary window");

    // Build the winit event loop before handing off to the game runtime.
    // On macOS the event loop MUST be created and run on the main thread.
    let event_loop = EventLoop::with_user_event()
        .build()
        .expect("Failed to create event loop");

    // env!("CARGO_MANIFEST_DIR") expands to THIS project's root at compile
    // time — must be here in main.rs, not inside pulsar_game, so it resolves
    // to the game project directory rather than the engine library directory.
    let project_root = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));

    // The primary window is opened before begin_play fires on any actor.
    // The default map from .pulsar/project/project.toml is loaded into it.
    // Additional windows can be opened at runtime via WindowManager::open().
    game.run_with_windows(event_loop, WindowDescriptor {{
        title: env!("CARGO_PKG_NAME").into(),
        width: 1280,
        height: 720,
        editor_mode: false,
    }}, project_root);
}}
"#
        );

        virtual_fs::write_file(&main_rs, main_content.as_bytes())
            .map_err(|e| format!("Failed to write src/main.rs: {e}"))?;
    }

    // ── lib.rs — Play-In-Editor embedding shim (issue #243) ───────────────────
    ensure_embed_lib(&src_dir)?;

    // ── engine_main.rs — level bootstrap with prefab spawning ─────────────────
    ensure_engine_main(project_root, &src_dir)?;

    // ── Pulsar/level.json — default level configuration ───────────────────────
    ensure_level_json(project_root)?;

    // ── Engine primitive assets ───────────────────────────────────────────────
    // Copy engine-bundled primitives (SM_Cube.fbx etc.) into the game project's
    // assets directory so they're available at runtime without the source tree.
    ensure_engine_primitives(project_root);

    Ok(())
}

/// Copy engine primitive meshes into `<project>/assets/meshes/primitives/`.
///
/// The source is the engine's own `assets/` directory, located relative to this
/// crate at compile time.  Missing files are copied; existing files are skipped
/// so user-overrides aren't clobbered.
fn ensure_engine_primitives(project_root: &Path) {
    // CARGO_MANIFEST_DIR = <repo>/crates/engine_backend  →  ../../  = <repo>
    const ENGINE_ASSETS: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../../assets");

    let src_prims = std::path::Path::new(ENGINE_ASSETS).join("meshes/primitives");
    if !src_prims.exists() {
        tracing::debug!(
            "Engine primitives source not found at {}",
            src_prims.display()
        );
        return;
    }

    let dst_prims = project_root.join("assets/meshes/primitives");
    if let Err(e) = virtual_fs::create_dir_all(&dst_prims) {
        tracing::warn!("Could not create primitives dir: {e}");
        return;
    }

    let Ok(entries) = virtual_fs::list_dir(&src_prims) else {
        return;
    };
    for entry in entries {
        if !entry.name.ends_with(".fbx") {
            continue;
        }
        let src = src_prims.join(&entry.name);
        let dst = dst_prims.join(&entry.name);
        if dst.exists() {
            continue;
        } // don't overwrite user assets
        match virtual_fs::read_file(&src) {
            Ok(bytes) => {
                if let Err(e) = virtual_fs::write_file(&dst, &bytes) {
                    tracing::warn!("Failed to copy primitive {}: {e}", src.display());
                } else {
                    tracing::debug!("Copied engine primitive → {}", dst.display());
                }
            }
            Err(e) => {
                tracing::warn!("Failed to read primitive {}: {e}", src.display());
            }
        }
    }
}

// ── scripts/ — user gameplay script crates (#653) ────────────────────────────

/// Insert script-crate path dependencies into the baked manifest text.
///
/// `GAME_MANIFEST_DEPS` is `[dependencies] … [patch.*] …`; TOML forbids
/// reopening a table, so the entries are spliced in just before the FIRST
/// `[patch.` table header (or appended when there is none). The absolute
/// engine-checkout path matches the baked `pulsar_game` spec exactly, so
/// cargo unifies both references to one build.
fn splice_script_dependencies(manifest_deps: &str, crates: &[ScriptCrate]) -> String {
    if crates.is_empty() {
        return manifest_deps.to_string();
    }
    let mut lines = String::from(
        "\n# Gameplay script crates (#653): user-authored Rust gameplay code,\n\
         # compiled into this project's dylib automatically.\n",
    );
    for krate in crates {
        let dir = krate.dir_name.replace('\\', "/");
        lines.push_str(&format!(
            "{name} = {{ path = \"scripts/{dir}\" }}\n",
            name = krate.name
        ));
    }

    let splice_at = manifest_deps.find("\n[patch.").unwrap_or(manifest_deps.len());
    let mut out = String::with_capacity(manifest_deps.len() + lines.len());
    out.push_str(&manifest_deps[..splice_at]);
    out.push_str(&lines);
    out.push_str(&manifest_deps[splice_at..]);
    out
}

/// The `[workspace]` table making the project package the workspace root with
/// every script crate as a member, so one `cargo build` compiles them all.
/// Empty (no output) when there is nothing to list.
fn workspace_block(crates: &[ScriptCrate]) -> String {
    if crates.is_empty() {
        return String::new();
    }
    let mut out = String::from(
        "\n# The project package roots the workspace; gameplay script crates\n\
         # under scripts/ are members too (#653).\n[workspace]\nmembers = [\n",
    );
    for krate in crates {
        let dir = krate.dir_name.replace('\\', "/");
        out.push_str(&format!("    \"scripts/{dir}\",\n"));
    }
    out.push_str("]\n");
    out
}

/// Ensure the `scripts/` directory exists and contains at least one gameplay
/// script crate, scaffolding a starter (`<game>_scripts`) when none do.
///
/// NEVER overwrites existing files: the starter is only written when its
/// target files don't exist, so users own everything inside their crate after
/// first creation. Re-running on a project that already has script crates is
/// a no-op beyond creating the directory itself.
fn ensure_scripts_crate(project_root: &Path) -> Result<(), String> {
    let scripts_dir = project_root.join("scripts");
    virtual_fs::create_dir_all(&scripts_dir)
        .map_err(|e| format!("Failed to create scripts directory: {e}"))?;

    if !discover_script_crates(project_root).is_empty() {
        return Ok(());
    }

    // Derive the crate name from the project's own safe name so two projects
    // scaffolded side by side never collide on a shared dependency graph.
    let game_fallback = project_root
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("pulsar_project");
    let crate_dir = format!("{}_scripts", cargo_safe_name(game_fallback));
    let crate_root = scripts_dir.join(&crate_dir);

    let src_dir = crate_root.join("src");
    virtual_fs::create_dir_all(&src_dir)
        .map_err(|e| format!("Failed to create scripts crate directory: {e}"))?;

    let pulsar_game_path = engine_checkout_path("crates/core/pulsar_game");
    let manifest = format!(
        "# User gameplay scripts for this Pulsar project. Generated once by the\n\
         # Core Project Builder (#653); you own every line after that.\n\
         [package]\n\
         name = \"{crate_dir}\"\n\
         version = \"0.1.0\"\n\
         edition = \"2021\"\n\
         publish = false\n\n\
         [dependencies]\n\
         # Same absolute path the generated game manifest uses for `pulsar_game`,\n\
         # so both unify to ONE compiled copy of the engine runtime.\n\
         pulsar_game = {{ path = \"{pulsar_game_path}\" }}\n"
    );
    virtual_fs::write_file(&crate_root.join("Cargo.toml"), manifest.as_bytes())
        .map_err(|e| format!("Failed to write scripts Cargo.toml: {e}"))?;

    virtual_fs::write_file(&src_dir.join("lib.rs"), starter_lib_rs().as_bytes())
        .map_err(|e| format!("Failed to write scripts lib.rs: {e}"))?;
    tracing::info!(crate = %crate_dir, "Scaffolded starter gameplay script crate");

    Ok(())
}

/// Resolve a path relative to the ENGINE checkout this editor binary was built
/// from (same compile-time anchor as `ensure_engine_primitives`). Used for the
/// script crate's `pulsar_game` path dep; forward slashes keep the emitted
/// manifest portable across Windows/Unix checkouts.
fn engine_checkout_path(rel: &str) -> String {
    // CARGO_MANIFEST_DIR = <engine>/crates/core/engine_backend → ../../../ =
    // <engine> (same walk as build.rs's `workspace_root`).
    let resolved = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../../")
        .join(rel);
    let text = match std::fs::canonicalize(&resolved) {
        Ok(abs) => abs.to_string_lossy().into_owned(),
        Err(_) => resolved.to_string_lossy().into_owned(),
    };
    strip_windows_prefix(&text)
}

/// Windows `canonicalize()` returns an extended-length `\\?\` path, which
/// cargo rejects ("invalid path url") — same stripping rule as
/// `engine_backend/build.rs::absolute_path` (#652).
fn strip_windows_prefix(text: &str) -> String {
    let unified = text.replace('\\', "/");
    match unified.strip_prefix("//?/") {
        Some(stripped) => stripped.to_string(),
        None => unified,
    }
}

/// The starter `lib.rs`: one documented example actor + THE registration
/// entry point generated `engine_main.rs` calls. Doubles as the authoring
/// contract: register every actor type here via `register_actor::<T>`, which
/// is also what makes the type discoverable by the editor's add-object flow.
fn starter_lib_rs() -> String {
    r#"//! <project>_scripts — your gameplay code, hot-reloadable in Play-In-Editor.
//!
//! Register every actor type in [`register_scripts`] via
//! `game.register_actor::<Type>(...)`. That call stamps the entity with the
//! type identity PIE hot reload matches on (#653): press Play again while a
//! game runs and your actors re-bind to their existing entities instead of
//! spawning duplicates.

use pulsar_game::scene::{MeshAssetPath, StaticMeshComponent, Transform};
use pulsar_game::tick::TickLoop;
// Re-exports: script crates need no direct scenedb dependency — everything
// gameplay-facing rides on `pulsar_game`.
use pulsar_game::{Actor, Entity, World};

/// Rotates a cube forever. Spawned at the world origin on Play.
///
/// `begin_play` gives the entity something visible (absent-only: scene-provided
/// components always win), and `tick` mutates the LIVE `Transform` component —
/// the same row the renderer reads, so edits show next frame and survive reload.
pub struct Spinner {
    degrees_per_second: f32,
}

impl Actor for Spinner {
    fn begin_play(&mut self, entity: Entity, world: &mut World) {
        if world.get::<StaticMeshComponent>(entity).is_none() {
            world.insert(
                entity,
                StaticMeshComponent {
                    mesh_asset: MeshAssetPath::new("meshes/primitives/SM_Cube.fbx"),
                    ..Default::default()
                },
            );
        }
        if world.get::<Transform>(entity).is_none() {
            world.insert(entity, Transform::default());
        }
    }

    fn tick(&mut self, entity: Entity, world: &mut World) {
        // Fixed-step approximation; see the tutorial for a time-driven variant.
        if let Some(mut transform) = world.get_mut::<Transform>(entity) {
            transform.rotation[1] += self.degrees_per_second * 0.016;
        }
    }
}

/// Called by generated `engine_main.rs` on every build/play.
///
/// The explicit turbofish is REQUIRED by convention: it is the marker the
/// level editor scans to offer your types in the add-object flow.
pub fn register_scripts(game: &mut TickLoop) -> Result<(), String> {
    game.register_actor::<Spinner>(Spinner {
        degrees_per_second: 45.0,
    });
    Ok(())
}
"#
    .to_string()
}

// ── engine_main.rs ────────────────────────────────────────────────────────────

/// Level prefab entry deserialized from `Pulsar/level.json`.
#[derive(serde::Deserialize, Default)]
struct LevelPrefabEntry {
    class_name: String,
    #[serde(default = "default_spawn_count")]
    count: usize,
    #[serde(default)]
    variable_overrides: std::collections::HashMap<String, serde_json::Value>,
}

fn default_spawn_count() -> usize {
    1
}

/// Root structure of `Pulsar/level.json`.
#[derive(serde::Deserialize, Default)]
struct LevelConfig {
    #[serde(default)]
    prefabs: Vec<LevelPrefabEntry>,
}

/// Generate `src/lib.rs` — the Play-In-Editor (PiE) embedding shim.
///
/// When the editor builds the project as a `cdylib` (`cargo build --lib`) and
/// loads it for Play-In-Editor, it resolves these six `extern "C"` symbols. The
/// shim is deliberately thin: every entry point wraps a `catch_unwind` (unwinding
/// across the FFI boundary is UB) and delegates to `pulsar_game::embed`, where
/// the real logic lives type-checked against Helio. `pulsar_pie_init` hands the
/// project's own `engine_main::setup` to the embed layer so the same actor /
/// blueprint wiring the standalone binary uses runs inside the editor.
fn ensure_embed_lib(src_dir: &Path) -> Result<(), String> {
    let lib_rs = src_dir.join("lib.rs");

    let content = r#"//! Play-In-Editor embedding shim.  @generated-by-pulsar-embed-lib
//!
//! Regenerated by the Pulsar Core Project Builder. Exports the `pulsar_pie_*`
//! C-ABI symbols the editor loads when you press Play. Do not edit by hand —
//! remove the `@generated-by-pulsar-embed-lib` marker to opt out of regeneration.

use pulsar_game::embed;
use pulsar_pie_abi::{EngineContext, InputEvent, INIT_ERR, PIE_ABI_VERSION};

mod classes;
mod engine_main;

/// ABI revision this game was built against; the editor refuses to load on a
/// mismatch and asks the user to rebuild.
#[no_mangle]
pub extern "C" fn pulsar_pie_abi_version() -> u64 {
    PIE_ABI_VERSION
}

/// Build the embedded game: ECS world + offscreen Helio renderer on the editor's
/// GPU device. Returns `1` on success (and writes `ctx.out_texture`), `0` on
/// failure.
///
/// # Safety
/// `ctx` must point at a valid, host-populated `EngineContext`.
#[no_mangle]
pub unsafe extern "C" fn pulsar_pie_init(ctx: *mut EngineContext) -> u32 {
    std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| unsafe {
        embed::pie_init(ctx, engine_main::setup)
    }))
    .unwrap_or(INIT_ERR)
}

/// Advance simulation and render one frame into the offscreen target.
#[no_mangle]
pub extern "C" fn pulsar_pie_tick(delta_time: f32) {
    let _ = std::panic::catch_unwind(|| embed::pie_tick(delta_time));
}

/// Resize the offscreen render target.
#[no_mangle]
pub extern "C" fn pulsar_pie_resize(width: u32, height: u32) {
    let _ = std::panic::catch_unwind(|| embed::pie_resize(width, height));
}

/// Forward one input event from the editor's input abstraction.
///
/// # Safety
/// `ev` must be a valid pointer to an `InputEvent` for the duration of the call.
#[no_mangle]
pub unsafe extern "C" fn pulsar_pie_input(ev: *const InputEvent) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| unsafe {
        embed::pie_input(ev)
    }));
}

/// Tear down the embedded game before the editor unloads the library.
#[no_mangle]
pub extern "C" fn pulsar_pie_shutdown() {
    let _ = std::panic::catch_unwind(embed::pie_shutdown);
}
"#;

    // Only write when missing or still ours, so a user who deletes the marker to
    // customise the shim keeps their edits.
    let should_write = if lib_rs.exists() {
        virtual_fs::read_file(&lib_rs)
            .ok()
            .and_then(|b| String::from_utf8(b).ok())
            .map(|s| s.contains("@generated-by-pulsar-embed-lib"))
            .unwrap_or(true)
    } else {
        true
    };

    if should_write {
        virtual_fs::write_file(&lib_rs, content.as_bytes())
            .map_err(|e| format!("Failed to write src/lib.rs: {e}"))?;
    }

    Ok(())
}

/// Generate `src/engine_main.rs`.
///
/// Produces a `pub fn setup(game: &mut TickLoop)` function that:
/// 1. Spawns native actor classes declared in `Pulsar/level.json` into the
///    `TickLoop`'s `ActorRegistry` and shared scene store so they receive
///    `tick` every frame (the store is the ONE SceneDB world, also read by
///    renderers -- Pulsar-Native#634).
/// 2. Scans `src/classes/*/events/.build/bytecode.json` for VM-compiled blueprints,
///    loads them into a `BlueprintDispatcher`, and wires the dispatcher into the
///    `TickLoop`. `setup()` runs before the primary window/scene exist, so
///    `begin_play`/`end_play` are deliberately NOT dispatched here — the
///    `TickLoop` fires `begin_play` on its first tick (once the window is open)
///    and `end_play` on shutdown, the same lifecycle ordering native actors get.
///
/// The file is regenerated whenever the Pulsar editor compiles a blueprint.
/// Remove the `@generated-by-pulsar-engine_main` marker to opt out of regeneration.
fn ensure_engine_main(project_root: &Path, src_dir: &Path) -> Result<(), String> {
    let engine_main_rs = src_dir.join("engine_main.rs");

    // Always regenerate — the JSON/blueprint files are the source of truth.
    // Users who want to customise this file should not use the generated project.

    // Read the level config to embed native actor spawn calls.
    // Fall back to an empty config if the file doesn't exist yet.
    let level_json_path = project_root.join("Pulsar").join("level.json");
    let level_config: LevelConfig = if level_json_path.exists() {
        virtual_fs::read_file(&level_json_path)
            .ok()
            .and_then(|bytes| String::from_utf8(bytes).ok())
            .and_then(|s| serde_json::from_str(&s).ok())
            .unwrap_or_default()
    } else {
        LevelConfig::default()
    };

    // Build native actor spawn statements — actors go directly into
    // game.actors, registered against the shared scene store's World.
    let spawn_stmts: String = level_config
        .prefabs
        .iter()
        .flat_map(|entry| {
            let count = entry.count.max(1);
            (0..count).map(move |i| {
                let class = &entry.class_name;
                let note = if count > 1 {
                    format!(" ({}/{})", i + 1, count)
                } else {
                    String::new()
                };
                format!(
                    "    {{\n        tracing::info!(\"Spawning {class}{note}\");\n        \
                     // Registered through `register_actor` (#653): the entity is\n        \
                     // stamped with the class's type identity, so a PIE hot reload\n        \
                     // re-binds THIS class to its existing entities instead of\n        \
                     // spawning duplicates. begin_play hydrates declared components\n        \
                     // absent-only, so scene-provided values always win.\n        \
                     game.register_actor(classes::{class}::new());\n    }}\n"
                )
            })
        })
        .collect();

    let native_spawn_body = if spawn_stmts.is_empty() {
        "    // No native prefabs configured — add entries to Pulsar/level.json.\n".to_string()
    } else {
        spawn_stmts
    };

    // One registration line per gameplay script crate under scripts/ (#653).
    // `?` propagates into setup()'s Result so a broken crate fails Play loudly
    // instead of silently missing actors.
    let script_calls: String = discover_script_crates(project_root)
        .iter()
        .map(|krate| {
            format!(
                "    // User gameplay crate `scripts/{dir}`:\n    \
                 {name}::register_scripts(game)?;\n",
                dir = krate.dir_name,
                name = krate.name
            )
        })
        .collect();
    let script_section = if script_calls.is_empty() {
        "    // No gameplay script crates yet — add one under scripts/ (see docs).\n"
            .to_string()
    } else {
        format!(
            "    // ── Gameplay script crates (scripts/) ──────────────────────────────\n\
             // Each crate registers its actors through TickLoop::register_actor,\n\
             // which stamps entity identities PIE hot reload re-binds to (#653).\n{script_calls}"
        )
    };

    let content = format!(
        r#"//! engine_main — level bootstrap.  @generated-by-pulsar-engine_main
//!
//! This file is regenerated by the Pulsar editor whenever you compile a blueprint.
//! To prevent regeneration, remove the `@generated-by-pulsar-engine_main` marker.
//!
//! Native prefabs are controlled by `Pulsar/level.json`.
//! Gameplay script crates under `scripts/` are auto-discovered (#653).
//! VM blueprints are auto-discovered from `src/classes/*/events/.build/bytecode.json`.

use pulsar_game::prelude::*;
use pulsar_game::blueprint_runtime::BlueprintDispatcher;
use std::sync::{{Arc, Mutex}};

/// Set up the level: spawn native actors, register gameplay script crates and
/// load VM-compiled blueprints.
///
/// Called once from `main()` before `game.run_blocking()`.
/// - Native actors + script-crate actors are registered into the tick loop's
///   shared world and receive `tick` every frame (via `register_actor`, which
///   also makes them hot-reload-safe in Play-In-Editor).
/// - VM blueprints are loaded into `game.blueprint_dispatcher`; the `TickLoop`
///   dispatches `BlueprintEvent::Tick` to each instance after every frame.
pub fn setup(game: &mut TickLoop) -> Result<(), String> {{
    // ── Native actors (from Pulsar/level.json) ────────────────────────────────
{native_spawn_body}
{script_section}
    // ── VM blueprint discovery ────────────────────────────────────────────────
    //
    // Scan src/classes/*/events/.build/bytecode.json.
    // Each file was written by the Blueprint Editor's BytecodeVm compile path.
    // The function-pointer slots are zero here; BlueprintDispatcher::new() calls
    // BpExecutor::prepare() which patches them from the embedded pulsar_std dylib.
    let classes_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("src")
        .join("classes");

    if classes_dir.exists() {{
        match BlueprintDispatcher::new() {{
            Ok(mut dispatcher) => {{
                let mut vm_loaded: usize = 0;

                let read_dir = std::fs::read_dir(&classes_dir)
                    .map_err(|e| format!("Cannot read classes dir: {{e}}"))?;

                for entry in read_dir.flatten() {{
                    if !entry.path().is_dir() {{
                        continue;
                    }}

                    let build_path = entry
                        .path()
                        .join("events")
                        .join(".build")
                        .join("bytecode.json");

                    if !build_path.exists() {{
                        continue;
                    }}

                    let class_name = entry.file_name().to_string_lossy().into_owned();
                    // Each VM class gets a single default instance.
                    // For per-level multi-instance spawning, add support in level.json.
                    let object_id = format!("{{class_name}}__vm_default");

                    match dispatcher.register_instance(object_id.clone(), &build_path, None) {{
                        Ok(()) => {{
                            // `begin_play` is intentionally NOT fired here — `setup()` runs
                            // before the primary window/GPU surface/scene exist. The
                            // TickLoop dispatches it on the first tick (after the window is
                            // open), so blueprint begin_play logic sees a ready world —
                            // the same ordering native actors get from `ActorRegistry`.
                            vm_loaded += 1;
                            tracing::info!("VM blueprint loaded: {{class_name}} → {{object_id}}");
                        }}
                        Err(e) => {{
                            tracing::warn!(
                                "Failed to load VM blueprint '{{class_name}}': {{e}}"
                            );
                        }}
                    }}
                }}

                if vm_loaded > 0 {{
                    game.blueprint_dispatcher = Some(Arc::new(Mutex::new(dispatcher)));
                    tracing::info!(
                        "VM blueprint runtime active — {{vm_loaded}} class(es) loaded"
                    );
                }} else {{
                    tracing::debug!("No VM blueprints found in {{}}",  classes_dir.display());
                }}
            }}
            Err(e) => {{
                // Non-fatal: native actors still run without the VM runtime.
                tracing::warn!("Could not initialise BlueprintDispatcher: {{e}}");
            }}
        }}
    }}

    Ok(())
}}
"#,
    );

    virtual_fs::write_file(&engine_main_rs, content.as_bytes())
        .map_err(|e| format!("Failed to write src/engine_main.rs: {e}"))
}

// ── Pulsar/level.json ─────────────────────────────────────────────────────────

/// Ensure `Pulsar/level.json` exists with a reasonable starter template.
fn ensure_level_json(project_root: &Path) -> Result<(), String> {
    let pulsar_dir = project_root.join("Pulsar");
    virtual_fs::create_dir_all(&pulsar_dir)
        .map_err(|e| format!("Failed to create Pulsar directory: {e}"))?;

    let level_json = pulsar_dir.join("level.json");
    if level_json.exists() {
        return Ok(());
    }

    let default_content = serde_json::json!({
        "$schema": "https://schema.pulsar-engine.dev/level.json",
        "prefabs": []
    });

    let pretty = serde_json::to_string_pretty(&default_content)
        .map_err(|e| format!("Failed to serialise level.json template: {e}"))?;

    virtual_fs::write_file(&level_json, pretty.as_bytes())
        .map_err(|e| format!("Failed to write Pulsar/level.json: {e}"))
}

#[cfg(test)]
mod tests {
    use super::{
        cargo_safe_name, ensure_core_cargo_toml, ensure_scripts_crate, splice_script_dependencies,
        workspace_block, HELIO_GIT_REVISION,
    };
    use super::super::native_scripts::{discover_script_crates, discover_script_actors};

    #[test]
    fn generated_project_pins_the_workspace_helio_revision() {
        let project = tempfile::tempdir().unwrap();
        ensure_core_cargo_toml(project.path()).unwrap();

        let manifest = std::fs::read_to_string(project.path().join("Cargo.toml")).unwrap();
        let expected = format!(
            "helio = {{ git = \"https://github.com/Far-Beyond-Pulsar/Helio\", rev = \"{HELIO_GIT_REVISION}\" }}"
        );
        assert!(manifest.lines().any(|line| line == expected));
        assert!(!manifest
            .lines()
            .any(|line| { line.starts_with("helio = ") && !line.contains("rev = ") }));
    }

    /// #653 scaffolding: a fresh project gets a starter scripts crate whose
    /// manifest points at THIS engine checkout's pulsar_game; a second run
    /// must never clobber user edits inside an existing crate.
    #[test]
    fn scripts_crate_is_scaffolded_once_and_never_overwritten() {
        let outer = tempfile::tempdir().unwrap();
        // Deterministic project dir name: the scaffolded crate derives its
        // name from the project folder.
        let project = outer.path().join("My Game");
        std::fs::create_dir_all(&project).unwrap();

        ensure_scripts_crate(&project).unwrap();
        let dir_name = format!("{}_scripts", cargo_safe_name("My Game"));
        let crate_root = project.join("scripts").join(&dir_name);
        let lib_rs = crate_root.join("src").join("lib.rs");

        assert!(crate_root.join("Cargo.toml").exists(), "manifest written");
        assert!(lib_rs.exists(), "starter lib.rs written");
        assert_eq!(
            discover_script_crates(&project).len(),
            1,
            "scaffolded crate is discoverable"
        );
        assert!(
            discover_script_actors(&project)
                .iter()
                .any(|a| a.type_name == "Spinner"),
            "the starter registers its example actor via the scannable convention"
        );

        // Simulate the user editing their crate, then re-run bootstrap.
        std::fs::write(&lib_rs, "// my precious edit\n").unwrap();
        ensure_scripts_crate(&project).unwrap();
        assert_eq!(
            std::fs::read_to_string(&lib_rs).unwrap(),
            "// my precious edit\n",
            "user code must survive regeneration"
        );
    }

    /// With a scripts crate present, the generated game manifest gains: the
    /// path dependency INSIDE [dependencies] (before any [patch.*] table) and
    /// a [workspace] block listing the member.
    #[test]
    fn manifest_wires_script_crates_into_dependencies_and_workspace() {
        let outer = tempfile::tempdir().unwrap();
        let project = outer.path().join("pulsar_project");
        std::fs::create_dir_all(&project).unwrap();
        ensure_scripts_crate(&project).unwrap();
        ensure_core_cargo_toml(&project).unwrap();

        let manifest = std::fs::read_to_string(project.join("Cargo.toml")).unwrap();
        let deps_pos = manifest.find("[dependencies]").expect("[dependencies]");
        let patch_pos = manifest.find("[patch.").expect("baked patch tables");
        let dep_line = manifest
            .lines()
            .find(|l| l.starts_with("pulsar_project_scripts = "))
            .expect("script crate path dependency emitted");
        assert!(
            manifest.rfind(dep_line).unwrap() > deps_pos
                && manifest.rfind(dep_line).unwrap() < patch_pos,
            "dep line must sit inside the baked [dependencies] table"
        );
        let workspace_pos = manifest.find("[workspace]").expect("[workspace]");
        assert!(workspace_pos > patch_pos, "workspace table comes last");
        assert!(manifest.contains("\"scripts/pulsar_project_scripts\""));
    }

    /// Splice placement unit test: entries land before the first patch table,
    /// never after it (TOML forbids reopening a table).
    #[test]
    fn splice_puts_script_deps_inside_the_dependencies_table() {
        let baked = "[dependencies]\npulsar_game = { path = \"x\" }\n\n[patch.\"u\"]\nfoo = {}\n";
        let out = splice_script_dependencies(
            baked,
            &[super::ScriptCrate {
                name: "my_scripts".into(),
                dir_name: "my_scripts".into(),
            }],
        );
        let dep = out.find("my_scripts = ").unwrap();
        let deps_table = out.find("[dependencies]").unwrap();
        let patch = out.find("[patch.").unwrap();
        assert!(deps_table < dep && dep < patch);

        // No crates → byte-identical passthrough.
        assert_eq!(splice_script_dependencies(baked, &[]), baked);
        assert!(workspace_block(&[]).is_empty());
    }
}
