use std::path::Path;

use engine_fs::virtual_fs;
use engine_state::{register_default_settings, ProjectSettings};

/// Helio revision selected by the Pulsar workspace.
///
/// The build script derives this from `[workspace.dependencies]` and rejects
/// mismatched Helio package revisions. Generated games use the same revision
/// so their direct Helio values remain compatible with Pulsar's public API.
pub const HELIO_GIT_REVISION: &str = env!("PULSAR_HELIO_GIT_REVISION");

fn settings_string(
    settings: Option<&ProjectSettings>,
    owner: &str,
    key: &str,
    default: &str,
) -> String {
    settings
        .and_then(|s| s.get(owner, key))
        .and_then(|v| v.as_str().ok().map(str::to_string))
        .unwrap_or_else(|| default.to_string())
}

fn settings_bool(
    settings: Option<&ProjectSettings>,
    owner: &str,
    key: &str,
    default: bool,
) -> bool {
    settings
        .and_then(|s| s.get(owner, key))
        .and_then(|v| v.as_bool().ok())
        .unwrap_or(default)
}

fn cargo_safe_name(raw: &str) -> String {
    let lowered = raw.trim().to_ascii_lowercase();
    let mut out = String::with_capacity(lowered.len());
    for ch in lowered.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' || ch == '-' {
            out.push(ch);
        } else if ch.is_whitespace() {
            out.push('_');
        }
    }
    let out = out.trim_matches('_').to_string();
    if out.is_empty() {
        "pulsar_project".to_string()
    } else {
        out
    }
}

fn ensure_core_cargo_toml(project_root: &Path) -> Result<(), String> {
    // Register schemas once before any project settings reads.
    register_default_settings();

    let settings = ProjectSettings::new(project_root);
    if let Some(ref s) = settings {
        s.load_all();
    }

    let fallback_name = project_root
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("pulsar_project")
        .to_string();

    let project_name = settings_string(settings.as_ref(), "project", "name", &fallback_name);
    let crate_name = cargo_safe_name(&project_name);
    let version = settings_string(settings.as_ref(), "project", "version", "0.1.0");
    let description = settings_string(settings.as_ref(), "project", "description", "");
    let author = settings_string(settings.as_ref(), "project", "author", "");
    let license_spdx = settings_string(settings.as_ref(), "project", "license_spdx", "");
    let license = settings_string(settings.as_ref(), "project", "license", "MIT");
    let optimize = settings_bool(settings.as_ref(), "build", "optimize", false);
    let debug_symbols = settings_bool(settings.as_ref(), "build", "debug_symbols", true);

    let selected_license = if license_spdx.is_empty() {
        license
    } else {
        license_spdx
    };

    let cargo_toml_path = project_root.join("Cargo.toml");
    let should_write_cargo = if cargo_toml_path.exists() {
        let existing = String::from_utf8(
            virtual_fs::read_file(&cargo_toml_path)
                .map_err(|e| format!("Failed to read existing Cargo.toml: {e}"))?,
        )
        .map_err(|e| format!("Failed to read existing Cargo.toml as UTF-8: {e}"))?;

        existing.contains("Generated Pulsar game project:")
            || existing.contains("Generated by Pulsar Core Project Builder")
    } else {
        true
    };

    if !should_write_cargo {
        return Ok(());
    }

    let mut package_lines = vec![
        "# Generated by Pulsar Core Project Builder.".to_string(),
        "[package]".to_string(),
        format!("name = \"{}\"", crate_name),
        format!("version = \"{}\"", version),
        "edition = \"2021\"".to_string(),
        "publish = false".to_string(),
    ];

    if !description.is_empty() {
        package_lines.push(format!(
            "description = \"{}\"",
            description.replace('"', "\\\"")
        ));
    }
    if !author.is_empty() {
        package_lines.push(format!("authors = [\"{}\"]", author.replace('"', "\\\"")));
    }
    if !selected_license.is_empty() {
        package_lines.push(format!(
            "license = \"{}\"",
            selected_license.replace('"', "\\\"")
        ));
    }

    let profile_opt = if optimize { 3 } else { 0 };
    let profile_debug = if debug_symbols { 2 } else { 0 };

    let cargo_content = format!(
        "{}\n\n[dependencies]\n\
pulsar_game = {{ git = \"https://github.com/Far-Beyond-Pulsar/Pulsar-Native\" }}\n\
pulsar_std = {{ git = \"https://github.com/Far-Beyond-Pulsar/Pulsar-Native\" }}\n\
engine_class_derive = {{ git = \"https://github.com/Far-Beyond-Pulsar/Pulsar-Native\" }}\n\
pulsar_reflection = {{ git = \"https://github.com/Far-Beyond-Pulsar/Pulsar-Native\" }}\n\
serde = {{ version = \"1.0\", features = [\"derive\"] }}\n\
serde_json = \"1.0\"\n\
tracing = \"0.1\"\n\
tracing-subscriber = {{ version = \"0.3\", features = [\"fmt\", \"env-filter\"] }}\n\
helio = {{ git = \"https://github.com/Far-Beyond-Pulsar/Helio\", rev = \"{helio_rev}\" }}\n\
winit = \"0.30\"\n\n\
[profile.dev]\n\
opt-level = {}\n\
debug = {}\n",
        package_lines.join("\n"),
        profile_opt,
        profile_debug,
        helio_rev = HELIO_GIT_REVISION,
    );

    virtual_fs::write_file(&cargo_toml_path, cargo_content.as_bytes())
        .map_err(|e| format!("Failed to write Cargo.toml: {e}"))?;

    Ok(())
}

/// Ensure the core project bootstrap files exist and are up to date.
///
/// This is engine-owned project wiring. PBGC should only emit class files.
pub fn ensure_core_bootstrap(project_root: &Path) -> Result<(), String> {
    ensure_core_cargo_toml(project_root)?;

    let src_dir = project_root.join("src");
    virtual_fs::create_dir_all(&src_dir)
        .map_err(|e| format!("Failed to create src directory: {e}"))?;

    let classes_dir = src_dir.join("classes");
    virtual_fs::create_dir_all(&classes_dir)
        .map_err(|e| format!("Failed to create classes directory: {e}"))?;

    // Always regenerate classes/mod.rs from what's actually on disk.
    // This removes stale `pub mod Foo;` lines for deleted/renamed classes.
    let classes_mod = classes_dir.join("mod.rs");
    {
        let mut mod_content = "//! Auto-generated by Pulsar Core Project Builder.\n\
             //! DO NOT EDIT MANUALLY - YOUR CHANGES WILL BE OVERWRITTEN\n\n"
            .to_string();

        // Emit a `pub mod` declaration for every subdirectory that has a mod.rs.
        if let Ok(entries) = virtual_fs::list_dir(&classes_dir) {
            let mut names: Vec<String> = entries
                .into_iter()
                .filter(|e| e.is_dir)
                .filter(|e| {
                    let mod_rs_path = classes_dir.join(&e.name).join("mod.rs");
                    mod_rs_path.exists()
                })
                .map(|e| e.name.clone())
                .collect();
            names.sort();
            for name in names {
                mod_content.push_str(&format!("pub mod {};\n", name));
            }
        }

        virtual_fs::write_file(&classes_mod, mod_content.as_bytes())
            .map_err(|e| format!("Failed to write classes/mod.rs: {e}"))?;
    }

    // Always regenerate main.rs — the editor and JSON are the source of truth.
    let main_rs = src_dir.join("main.rs");
    {
        let project_name = project_root
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("pulsar_project");

        let main_content = format!(
            r#"//! {project_name} — generated by Pulsar Core Project Builder.

use pulsar_game::prelude::*;
use winit::event_loop::EventLoop;

mod classes;
mod engine_main;

fn main() {{
    tracing_subscriber::fmt()
        .with_env_filter(std::env::var("RUST_LOG").unwrap_or_else(|_| "info".into()))
        .init();

    tracing::info!("Starting {{}}", env!("CARGO_PKG_NAME"));

    let threads = std::thread::available_parallelism()
        .map(|n| n.get())
        .unwrap_or(4);

    let mut game = TickLoop::new(TickMode::default(), threads);

    if let Err(e) = engine_main::setup(&mut game) {{
        tracing::error!("Level setup failed: {{e}}");
        std::process::exit(1);
    }}

    tracing::info!("World ready — opening primary window");

    // Build the winit event loop before handing off to the game runtime.
    // On macOS the event loop MUST be created and run on the main thread.
    let event_loop = EventLoop::with_user_event()
        .build()
        .expect("Failed to create event loop");

    // env!("CARGO_MANIFEST_DIR") expands to THIS project's root at compile
    // time — must be here in main.rs, not inside pulsar_game, so it resolves
    // to the game project directory rather than the engine library directory.
    let project_root = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));

    // The primary window is opened before begin_play fires on any actor.
    // The default map from .pulsar/project/project.toml is loaded into it.
    // Additional windows can be opened at runtime via WindowManager::open().
    game.run_with_windows(event_loop, WindowDescriptor {{
        title: env!("CARGO_PKG_NAME").into(),
        width: 1280,
        height: 720,
        editor_mode: false,
    }}, project_root);
}}
"#
        );

        virtual_fs::write_file(&main_rs, main_content.as_bytes())
            .map_err(|e| format!("Failed to write src/main.rs: {e}"))?;
    }

    // ── engine_main.rs — level bootstrap with prefab spawning ─────────────────
    ensure_engine_main(project_root, &src_dir)?;

    // ── Pulsar/level.json — default level configuration ───────────────────────
    ensure_level_json(project_root)?;

    // ── Engine primitive assets ───────────────────────────────────────────────
    // Copy engine-bundled primitives (SM_Cube.fbx etc.) into the game project's
    // assets directory so they're available at runtime without the source tree.
    ensure_engine_primitives(project_root);

    Ok(())
}

/// Copy engine primitive meshes into `<project>/assets/meshes/primitives/`.
///
/// The source is the engine's own `assets/` directory, located relative to this
/// crate at compile time.  Missing files are copied; existing files are skipped
/// so user-overrides aren't clobbered.
fn ensure_engine_primitives(project_root: &Path) {
    // CARGO_MANIFEST_DIR = <repo>/crates/engine_backend  →  ../../  = <repo>
    const ENGINE_ASSETS: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../../assets");

    let src_prims = std::path::Path::new(ENGINE_ASSETS).join("meshes/primitives");
    if !src_prims.exists() {
        tracing::debug!(
            "Engine primitives source not found at {}",
            src_prims.display()
        );
        return;
    }

    let dst_prims = project_root.join("assets/meshes/primitives");
    if let Err(e) = virtual_fs::create_dir_all(&dst_prims) {
        tracing::warn!("Could not create primitives dir: {e}");
        return;
    }

    let Ok(entries) = virtual_fs::list_dir(&src_prims) else {
        return;
    };
    for entry in entries {
        if !entry.name.ends_with(".fbx") {
            continue;
        }
        let src = src_prims.join(&entry.name);
        let dst = dst_prims.join(&entry.name);
        if dst.exists() {
            continue;
        } // don't overwrite user assets
        match virtual_fs::read_file(&src) {
            Ok(bytes) => {
                if let Err(e) = virtual_fs::write_file(&dst, &bytes) {
                    tracing::warn!("Failed to copy primitive {}: {e}", src.display());
                } else {
                    tracing::debug!("Copied engine primitive → {}", dst.display());
                }
            }
            Err(e) => {
                tracing::warn!("Failed to read primitive {}: {e}", src.display());
            }
        }
    }
}

// ── engine_main.rs ────────────────────────────────────────────────────────────

/// Level prefab entry deserialized from `Pulsar/level.json`.
#[derive(serde::Deserialize, Default)]
struct LevelPrefabEntry {
    class_name: String,
    #[serde(default = "default_spawn_count")]
    count: usize,
    #[serde(default)]
    variable_overrides: std::collections::HashMap<String, serde_json::Value>,
}

fn default_spawn_count() -> usize {
    1
}

/// Root structure of `Pulsar/level.json`.
#[derive(serde::Deserialize, Default)]
struct LevelConfig {
    #[serde(default)]
    prefabs: Vec<LevelPrefabEntry>,
}

/// Generate `src/engine_main.rs`.
///
/// Produces a `pub fn setup(game: &mut TickLoop)` function that:
/// 1. Spawns native actor classes declared in `Pulsar/level.json` into the
///    `TickLoop`'s `ActorRegistry` and `World` so they receive `tick` every frame.
/// 2. Scans `src/classes/*/events/.build/bytecode.json` for VM-compiled blueprints,
///    loads them into a `BlueprintDispatcher`, and wires the dispatcher into the
///    `TickLoop`. `setup()` runs before the primary window/scene exist, so
///    `begin_play`/`end_play` are deliberately NOT dispatched here — the
///    `TickLoop` fires `begin_play` on its first tick (once the window is open)
///    and `end_play` on shutdown, the same lifecycle ordering native actors get.
///
/// The file is regenerated whenever the Pulsar editor compiles a blueprint.
/// Remove the `@generated-by-pulsar-engine_main` marker to opt out of regeneration.
fn ensure_engine_main(project_root: &Path, src_dir: &Path) -> Result<(), String> {
    let engine_main_rs = src_dir.join("engine_main.rs");

    // Always regenerate — the JSON/blueprint files are the source of truth.
    // Users who want to customise this file should not use the generated project.

    // Read the level config to embed native actor spawn calls.
    // Fall back to an empty config if the file doesn't exist yet.
    let level_json_path = project_root.join("Pulsar").join("level.json");
    let level_config: LevelConfig = if level_json_path.exists() {
        virtual_fs::read_file(&level_json_path)
            .ok()
            .and_then(|bytes| String::from_utf8(bytes).ok())
            .and_then(|s| serde_json::from_str(&s).ok())
            .unwrap_or_default()
    } else {
        LevelConfig::default()
    };

    // Build native actor spawn statements — actors go directly into game.actors.
    let spawn_stmts: String = level_config
        .prefabs
        .iter()
        .flat_map(|entry| {
            let count = entry.count.max(1);
            (0..count).map(move |i| {
                let class = &entry.class_name;
                let note = if count > 1 {
                    format!(" ({}/{})", i + 1, count)
                } else {
                    String::new()
                };
                format!(
                    "    {{\n        tracing::info!(\"Spawning {class}{note}\");\n        \
                     let actor = classes::{class}::new();\n        \
                     game.actors.register(actor, &mut game.world);\n    }}\n"
                )
            })
        })
        .collect();

    let native_spawn_body = if spawn_stmts.is_empty() {
        "    // No native prefabs configured — add entries to Pulsar/level.json.\n".to_string()
    } else {
        spawn_stmts
    };

    let content = format!(
        r#"//! engine_main — level bootstrap.  @generated-by-pulsar-engine_main
//!
//! This file is regenerated by the Pulsar editor whenever you compile a blueprint.
//! To prevent regeneration, remove the `@generated-by-pulsar-engine_main` marker.
//!
//! Native prefabs are controlled by `Pulsar/level.json`.
//! VM blueprints are auto-discovered from `src/classes/*/events/.build/bytecode.json`.

use pulsar_game::prelude::*;
use pulsar_game::blueprint_runtime::BlueprintDispatcher;
use std::sync::{{Arc, Mutex}};

/// Set up the level: spawn native actors and load VM-compiled blueprints.
///
/// Called once from `main()` before `game.run_blocking()`.
/// - Native actors are registered into `game.actors` and receive `tick` every frame.
/// - VM blueprints are loaded into `game.blueprint_dispatcher`; the `TickLoop`
///   dispatches `BlueprintEvent::Tick` to each instance after every frame.
pub fn setup(game: &mut TickLoop) -> Result<(), String> {{
    // ── Native actors (from Pulsar/level.json) ────────────────────────────────
{native_spawn_body}
    // ── VM blueprint discovery ────────────────────────────────────────────────
    //
    // Scan src/classes/*/events/.build/bytecode.json.
    // Each file was written by the Blueprint Editor's BytecodeVm compile path.
    // The function-pointer slots are zero here; BlueprintDispatcher::new() calls
    // BpExecutor::prepare() which patches them from the embedded pulsar_std dylib.
    let classes_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("src")
        .join("classes");

    if classes_dir.exists() {{
        match BlueprintDispatcher::new() {{
            Ok(mut dispatcher) => {{
                let mut vm_loaded: usize = 0;

                let read_dir = std::fs::read_dir(&classes_dir)
                    .map_err(|e| format!("Cannot read classes dir: {{e}}"))?;

                for entry in read_dir.flatten() {{
                    if !entry.path().is_dir() {{
                        continue;
                    }}

                    let build_path = entry
                        .path()
                        .join("events")
                        .join(".build")
                        .join("bytecode.json");

                    if !build_path.exists() {{
                        continue;
                    }}

                    let class_name = entry.file_name().to_string_lossy().into_owned();
                    // Each VM class gets a single default instance.
                    // For per-level multi-instance spawning, add support in level.json.
                    let object_id = format!("{{class_name}}__vm_default");

                    match dispatcher.register_instance(object_id.clone(), &build_path, None) {{
                        Ok(()) => {{
                            // `begin_play` is intentionally NOT fired here — `setup()` runs
                            // before the primary window/GPU surface/scene exist. The
                            // TickLoop dispatches it on the first tick (after the window is
                            // open), so blueprint begin_play logic sees a ready world —
                            // the same ordering native actors get from `ActorRegistry`.
                            vm_loaded += 1;
                            tracing::info!("VM blueprint loaded: {{class_name}} → {{object_id}}");
                        }}
                        Err(e) => {{
                            tracing::warn!(
                                "Failed to load VM blueprint '{{class_name}}': {{e}}"
                            );
                        }}
                    }}
                }}

                if vm_loaded > 0 {{
                    game.blueprint_dispatcher = Some(Arc::new(Mutex::new(dispatcher)));
                    tracing::info!(
                        "VM blueprint runtime active — {{vm_loaded}} class(es) loaded"
                    );
                }} else {{
                    tracing::debug!("No VM blueprints found in {{}}",  classes_dir.display());
                }}
            }}
            Err(e) => {{
                // Non-fatal: native actors still run without the VM runtime.
                tracing::warn!("Could not initialise BlueprintDispatcher: {{e}}");
            }}
        }}
    }}

    Ok(())
}}
"#,
    );

    virtual_fs::write_file(&engine_main_rs, content.as_bytes())
        .map_err(|e| format!("Failed to write src/engine_main.rs: {e}"))
}

// ── Pulsar/level.json ─────────────────────────────────────────────────────────

/// Ensure `Pulsar/level.json` exists with a reasonable starter template.
fn ensure_level_json(project_root: &Path) -> Result<(), String> {
    let pulsar_dir = project_root.join("Pulsar");
    virtual_fs::create_dir_all(&pulsar_dir)
        .map_err(|e| format!("Failed to create Pulsar directory: {e}"))?;

    let level_json = pulsar_dir.join("level.json");
    if level_json.exists() {
        return Ok(());
    }

    let default_content = serde_json::json!({
        "$schema": "https://schema.pulsar-engine.dev/level.json",
        "prefabs": []
    });

    let pretty = serde_json::to_string_pretty(&default_content)
        .map_err(|e| format!("Failed to serialise level.json template: {e}"))?;

    virtual_fs::write_file(&level_json, pretty.as_bytes())
        .map_err(|e| format!("Failed to write Pulsar/level.json: {e}"))
}

#[cfg(test)]
mod tests {
    use super::{ensure_core_cargo_toml, HELIO_GIT_REVISION};

    #[test]
    fn generated_project_pins_the_workspace_helio_revision() {
        let project = tempfile::tempdir().unwrap();
        ensure_core_cargo_toml(project.path()).unwrap();

        let manifest = std::fs::read_to_string(project.path().join("Cargo.toml")).unwrap();
        let expected = format!(
            "helio = {{ git = \"https://github.com/Far-Beyond-Pulsar/Helio\", rev = \"{HELIO_GIT_REVISION}\" }}"
        );
        assert!(manifest.lines().any(|line| line == expected));
        assert!(!manifest
            .lines()
            .any(|line| { line.starts_with("helio = ") && !line.contains("rev = ") }));
    }
}
