use std::path::Path;

/// Ensure the core project bootstrap files exist and are up to date.
///
/// This is engine-owned project wiring. PBGC should only emit class files.
pub fn ensure_core_bootstrap(project_root: &Path) -> Result<(), String> {
    let src_dir = project_root.join("src");
    std::fs::create_dir_all(&src_dir)
        .map_err(|e| format!("Failed to create src directory: {e}"))?;

    let classes_dir = src_dir.join("classes");
    std::fs::create_dir_all(&classes_dir)
        .map_err(|e| format!("Failed to create classes directory: {e}"))?;

    let classes_mod = classes_dir.join("mod.rs");
    if !classes_mod.exists() {
        std::fs::write(
            &classes_mod,
            "//! Generated by Pulsar Core Project Builder.\n",
        )
        .map_err(|e| format!("Failed to write classes/mod.rs: {e}"))?;
    }

    let main_rs = src_dir.join("main.rs");
    let should_write_main = if main_rs.exists() {
        let existing = std::fs::read_to_string(&main_rs)
            .map_err(|e| format!("Failed to read existing main.rs: {e}"))?;

        // Migrate previously generated stale bootstrap.
        existing.contains("generated by Pulsar Blueprint Compiler")
            || existing.contains("mod blueprints;")
    } else {
        true
    };

    if should_write_main {
        let project_name = project_root
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("pulsar_project");

        let main_content = format!(
            r#"//! {project_name} — generated by Pulsar Core Project Builder.

use pulsar_game::prelude::*;

mod classes;

fn main() {{
    tracing_subscriber::fmt()
        .with_env_filter(std::env::var("RUST_LOG").unwrap_or_else(|_| "info".into()))
        .init();

    tracing::info!("Starting {{}}", env!("CARGO_PKG_NAME"));

    let threads = std::thread::available_parallelism()
        .map(|n| n.get())
        .unwrap_or(4);

    let mut game = TickLoop::new(TickMode::default(), threads);

    tracing::info!("World ready — entering tick loop");
    game.run_blocking();
}}
"#
        );

        std::fs::write(&main_rs, main_content)
            .map_err(|e| format!("Failed to write src/main.rs: {e}"))?;
    }

    Ok(())
}
