use std::path::Path;

use engine_state::{register_default_settings, ProjectSettings};

fn settings_string(
    settings: Option<&ProjectSettings>,
    owner: &str,
    key: &str,
    default: &str,
) -> String {
    settings
        .and_then(|s| s.get(owner, key))
        .and_then(|v| v.as_str().ok().map(str::to_string))
        .unwrap_or_else(|| default.to_string())
}

fn settings_bool(
    settings: Option<&ProjectSettings>,
    owner: &str,
    key: &str,
    default: bool,
) -> bool {
    settings
        .and_then(|s| s.get(owner, key))
        .and_then(|v| v.as_bool().ok())
        .unwrap_or(default)
}

fn cargo_safe_name(raw: &str) -> String {
    let lowered = raw.trim().to_ascii_lowercase();
    let mut out = String::with_capacity(lowered.len());
    for ch in lowered.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' || ch == '-' {
            out.push(ch);
        } else if ch.is_whitespace() {
            out.push('_');
        }
    }
    let out = out.trim_matches('_').to_string();
    if out.is_empty() {
        "pulsar_project".to_string()
    } else {
        out
    }
}

fn ensure_core_cargo_toml(project_root: &Path) -> Result<(), String> {
    // Register schemas once before any project settings reads.
    register_default_settings();

    let settings = ProjectSettings::new(project_root);
    if let Some(ref s) = settings {
        s.load_all();
    }

    let fallback_name = project_root
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("pulsar_project")
        .to_string();

    let project_name = settings_string(settings.as_ref(), "project", "name", &fallback_name);
    let crate_name = cargo_safe_name(&project_name);
    let version = settings_string(settings.as_ref(), "project", "version", "0.1.0");
    let description = settings_string(settings.as_ref(), "project", "description", "");
    let author = settings_string(settings.as_ref(), "project", "author", "");
    let license_spdx = settings_string(settings.as_ref(), "project", "license_spdx", "");
    let license = settings_string(settings.as_ref(), "project", "license", "MIT");
    let optimize = settings_bool(settings.as_ref(), "build", "optimize", false);
    let debug_symbols = settings_bool(settings.as_ref(), "build", "debug_symbols", true);

    let selected_license = if license_spdx.is_empty() {
        license
    } else {
        license_spdx
    };

    let cargo_toml_path = project_root.join("Cargo.toml");
    let should_write_cargo = if cargo_toml_path.exists() {
        let existing = std::fs::read_to_string(&cargo_toml_path)
            .map_err(|e| format!("Failed to read existing Cargo.toml: {e}"))?;

        existing.contains("Generated Pulsar game project:")
            || existing.contains("Generated by Pulsar Core Project Builder")
    } else {
        true
    };

    if !should_write_cargo {
        return Ok(());
    }

    let mut package_lines = vec![
        "# Generated by Pulsar Core Project Builder.".to_string(),
        "[package]".to_string(),
        format!("name = \"{}\"", crate_name),
        format!("version = \"{}\"", version),
        "edition = \"2021\"".to_string(),
        "publish = false".to_string(),
    ];

    if !description.is_empty() {
        package_lines.push(format!(
            "description = \"{}\"",
            description.replace('"', "\\\"")
        ));
    }
    if !author.is_empty() {
        package_lines.push(format!("authors = [\"{}\"]", author.replace('"', "\\\"")));
    }
    if !selected_license.is_empty() {
        package_lines.push(format!(
            "license = \"{}\"",
            selected_license.replace('"', "\\\"")
        ));
    }

    let profile_opt = if optimize { 3 } else { 0 };
    let profile_debug = if debug_symbols { 2 } else { 0 };

    let cargo_content = format!(
        "{}\n\n[dependencies]\n\
pulsar_game = {{ git = \"https://github.com/Far-Beyond-Pulsar/Pulsar-Native\" }}\n\
pulsar_std = {{ git = \"https://github.com/Far-Beyond-Pulsar/Pulsar-Native\" }}\n\
engine_class_derive = {{ git = \"https://github.com/Far-Beyond-Pulsar/Pulsar-Native\" }}\n\
pulsar_reflection = {{ git = \"https://github.com/Far-Beyond-Pulsar/Pulsar-Native\" }}\n\
serde = {{ version = \"1.0\", features = [\"derive\"] }}\n\
serde_json = \"1.0\"\n\
tracing = \"0.1\"\n\
tracing-subscriber = {{ version = \"0.3\", features = [\"fmt\", \"env-filter\"] }}\n\
helio = {{ git = \"https://github.com/Far-Beyond-Pulsar/Helio\" }}\n\n\
[profile.dev]\n\
opt-level = {}\n\
debug = {}\n",
        package_lines.join("\n"),
        profile_opt,
        profile_debug
    );

    std::fs::write(&cargo_toml_path, cargo_content)
        .map_err(|e| format!("Failed to write Cargo.toml: {e}"))?;

    Ok(())
}

/// Ensure the core project bootstrap files exist and are up to date.
///
/// This is engine-owned project wiring. PBGC should only emit class files.
pub fn ensure_core_bootstrap(project_root: &Path) -> Result<(), String> {
    ensure_core_cargo_toml(project_root)?;

    let src_dir = project_root.join("src");
    std::fs::create_dir_all(&src_dir)
        .map_err(|e| format!("Failed to create src directory: {e}"))?;

    let classes_dir = src_dir.join("classes");
    std::fs::create_dir_all(&classes_dir)
        .map_err(|e| format!("Failed to create classes directory: {e}"))?;

    let classes_mod = classes_dir.join("mod.rs");
    if !classes_mod.exists() {
        std::fs::write(
            &classes_mod,
            "//! Generated by Pulsar Core Project Builder.\n",
        )
        .map_err(|e| format!("Failed to write classes/mod.rs: {e}"))?;
    }

    let main_rs = src_dir.join("main.rs");
    let should_write_main = if main_rs.exists() {
        let existing = std::fs::read_to_string(&main_rs)
            .map_err(|e| format!("Failed to read existing main.rs: {e}"))?;

        // Migrate previously generated stale bootstrap.
        existing.contains("generated by Pulsar Blueprint Compiler")
            || existing.contains("mod blueprints;")
            || (existing.contains("generated by Pulsar Core Project Builder")
                && !existing.contains("mod engine_main;"))
    } else {
        true
    };

    if should_write_main {
        let project_name = project_root
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("pulsar_project");

        let main_content = format!(
            r#"//! {project_name} — generated by Pulsar Core Project Builder.

use pulsar_game::prelude::*;

mod classes;
mod engine_main;

fn main() {{
    tracing_subscriber::fmt()
        .with_env_filter(std::env::var("RUST_LOG").unwrap_or_else(|_| "info".into()))
        .init();

    tracing::info!("Starting {{}}", env!("CARGO_PKG_NAME"));

    engine_main::main();

    let threads = std::thread::available_parallelism()
        .map(|n| n.get())
        .unwrap_or(4);

    let mut game = TickLoop::new(TickMode::default(), threads);

    tracing::info!("World ready — entering tick loop");
    game.run_blocking();
}}
"#
        );

        std::fs::write(&main_rs, main_content)
            .map_err(|e| format!("Failed to write src/main.rs: {e}"))?;
    }

    // ── engine_main.rs — level bootstrap with prefab spawning ─────────────────
    ensure_engine_main(project_root, &src_dir)?;

    // ── Pulsar/level.json — default level configuration ───────────────────────
    ensure_level_json(project_root)?;

    Ok(())
}

// ── engine_main.rs ────────────────────────────────────────────────────────────

/// Level prefab entry deserialized from `Pulsar/level.json`.
#[derive(serde::Deserialize, Default)]
struct LevelPrefabEntry {
    class_name: String,
    #[serde(default = "default_spawn_count")]
    count: usize,
    #[serde(default)]
    variable_overrides: std::collections::HashMap<String, serde_json::Value>,
}

fn default_spawn_count() -> usize {
    1
}

/// Root structure of `Pulsar/level.json`.
#[derive(serde::Deserialize, Default)]
struct LevelConfig {
    #[serde(default)]
    prefabs: Vec<LevelPrefabEntry>,
}

/// Generate `src/engine_main.rs`.
///
/// This file contains the level bootstrap logic that reads `Pulsar/level.json`
/// and spawns the configured default prefabs on game start.
///
/// The file is regenerated if it does not exist or if it was previously generated
/// by Pulsar (detected via a marker comment).  Hand-edited files are preserved.
fn ensure_engine_main(project_root: &Path, src_dir: &Path) -> Result<(), String> {
    let engine_main_rs = src_dir.join("engine_main.rs");

    let should_write = if engine_main_rs.exists() {
        let existing = std::fs::read_to_string(&engine_main_rs)
            .map_err(|e| format!("Failed to read engine_main.rs: {e}"))?;
        existing.contains("@generated-by-pulsar-engine_main")
    } else {
        true
    };

    if !should_write {
        return Ok(());
    }

    // Read the level config now to embed spawn calls.
    // If the file doesn't exist yet we use an empty config.
    let level_json_path = project_root.join("Pulsar").join("level.json");
    let level_config: LevelConfig = if level_json_path.exists() {
        std::fs::read_to_string(&level_json_path)
            .ok()
            .and_then(|s| serde_json::from_str(&s).ok())
            .unwrap_or_default()
    } else {
        LevelConfig::default()
    };

    // Build the spawn statements.
    let spawn_stmts: String = level_config
        .prefabs
        .iter()
        .flat_map(|entry| {
            let count = entry.count.max(1);
            (0..count).map(move |i| {
                let class = &entry.class_name;
                // snake_case the class name for a helpful log message.
                let note = if count > 1 {
                    format!(" ({}/{})", i + 1, count)
                } else {
                    String::new()
                };
                format!(
                    "    {{\n        tracing::info!(\"Spawning {class}{note}\");\n        \
                     let actor = classes::{class}::new();\n        \
                     registry.register(actor, &mut world);\n    }}\n"
                )
            })
        })
        .collect();

    let spawn_body = if spawn_stmts.is_empty() {
        "    // No default prefabs configured — add entries to Pulsar/level.json.\n    \
         tracing::info!(\"No default prefabs configured.\");\n"
            .to_string()
    } else {
        spawn_stmts
    };

    let content = format!(
        r#"//! engine_main — level bootstrap.  @generated-by-pulsar-engine_main
//!
//! This file is regenerated by the Pulsar editor whenever you compile a blueprint.
//! To prevent regeneration, remove the `@generated-by-pulsar-engine_main` marker
//! from the first line.
//!
//! Default prefabs are controlled by `Pulsar/level.json`.

use pulsar_game::prelude::*;

/// Spawn the level's default prefabs and register them with the actor registry.
///
/// Called once from `main()` before the tick loop begins.
pub fn main() {{
    let mut world = World::new();
    let mut registry = ActorRegistry::new();

{spawn_body}
    tracing::info!(
        "Level initialised — {{}} actor(s) registered",
        registry.entries.len()
    );

    // The registry and world are intentionally dropped here.
    // In the full engine, they would be handed to the TickLoop and
    // driven by the schedule.  Hook this up to your game's main loop.
    let _ = (world, registry);
}}
"#
    );

    std::fs::write(&engine_main_rs, content)
        .map_err(|e| format!("Failed to write src/engine_main.rs: {e}"))
}

// ── Pulsar/level.json ─────────────────────────────────────────────────────────

/// Ensure `Pulsar/level.json` exists with a reasonable starter template.
fn ensure_level_json(project_root: &Path) -> Result<(), String> {
    let pulsar_dir = project_root.join("Pulsar");
    std::fs::create_dir_all(&pulsar_dir)
        .map_err(|e| format!("Failed to create Pulsar directory: {e}"))?;

    let level_json = pulsar_dir.join("level.json");
    if level_json.exists() {
        return Ok(());
    }

    let default_content = serde_json::json!({
        "$schema": "https://schema.pulsar-engine.dev/level.json",
        "prefabs": []
    });

    let pretty = serde_json::to_string_pretty(&default_content)
        .map_err(|e| format!("Failed to serialise level.json template: {e}"))?;

    std::fs::write(&level_json, pretty)
        .map_err(|e| format!("Failed to write Pulsar/level.json: {e}"))
}
