use std::path::Path;

use engine_state::{ProjectSettings, register_default_settings};

fn settings_string(settings: Option<&ProjectSettings>, owner: &str, key: &str, default: &str) -> String {
    settings
        .and_then(|s| s.get(owner, key))
        .and_then(|v| v.as_str().ok().map(str::to_string))
        .unwrap_or_else(|| default.to_string())
}

fn settings_bool(settings: Option<&ProjectSettings>, owner: &str, key: &str, default: bool) -> bool {
    settings
        .and_then(|s| s.get(owner, key))
        .and_then(|v| v.as_bool().ok())
        .unwrap_or(default)
}

fn cargo_safe_name(raw: &str) -> String {
    let lowered = raw.trim().to_ascii_lowercase();
    let mut out = String::with_capacity(lowered.len());
    for ch in lowered.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' || ch == '-' {
            out.push(ch);
        } else if ch.is_whitespace() {
            out.push('_');
        }
    }
    let out = out.trim_matches('_').to_string();
    if out.is_empty() {
        "pulsar_project".to_string()
    } else {
        out
    }
}

fn ensure_core_cargo_toml(project_root: &Path) -> Result<(), String> {
    // Register schemas once before any project settings reads.
    register_default_settings();

    let settings = ProjectSettings::new(project_root);
    if let Some(ref s) = settings {
        s.load_all();
    }

    let fallback_name = project_root
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("pulsar_project")
        .to_string();

    let project_name = settings_string(settings.as_ref(), "project", "name", &fallback_name);
    let crate_name = cargo_safe_name(&project_name);
    let version = settings_string(settings.as_ref(), "project", "version", "0.1.0");
    let description = settings_string(settings.as_ref(), "project", "description", "");
    let author = settings_string(settings.as_ref(), "project", "author", "");
    let license_spdx = settings_string(settings.as_ref(), "project", "license_spdx", "");
    let license = settings_string(settings.as_ref(), "project", "license", "MIT");
    let optimize = settings_bool(settings.as_ref(), "build", "optimize", false);
    let debug_symbols = settings_bool(settings.as_ref(), "build", "debug_symbols", true);

    let selected_license = if license_spdx.is_empty() {
        license
    } else {
        license_spdx
    };

    let cargo_toml_path = project_root.join("Cargo.toml");
    let should_write_cargo = if cargo_toml_path.exists() {
        let existing = std::fs::read_to_string(&cargo_toml_path)
            .map_err(|e| format!("Failed to read existing Cargo.toml: {e}"))?;

        existing.contains("Generated Pulsar game project:")
            || existing.contains("Generated by Pulsar Core Project Builder")
    } else {
        true
    };

    if !should_write_cargo {
        return Ok(());
    }

    let mut package_lines = vec![
        "# Generated by Pulsar Core Project Builder.".to_string(),
        "[package]".to_string(),
        format!("name = \"{}\"", crate_name),
        format!("version = \"{}\"", version),
        "edition = \"2021\"".to_string(),
        "publish = false".to_string(),
    ];

    if !description.is_empty() {
        package_lines.push(format!("description = \"{}\"", description.replace('"', "\\\"")));
    }
    if !author.is_empty() {
        package_lines.push(format!("authors = [\"{}\"]", author.replace('"', "\\\"")));
    }
    if !selected_license.is_empty() {
        package_lines.push(format!("license = \"{}\"", selected_license.replace('"', "\\\"")));
    }

    let profile_opt = if optimize { 3 } else { 0 };
    let profile_debug = if debug_symbols { 2 } else { 0 };

    let cargo_content = format!(
        "{}\n\n[dependencies]\n\
pulsar_game = {{ git = \"https://github.com/Far-Beyond-Pulsar/Pulsar-Native\" }}\n\
engine_class_derive = {{ git = \"https://github.com/Far-Beyond-Pulsar/Pulsar-Native\" }}\n\
tracing = \"0.1\"\n\
tracing-subscriber = {{ version = \"0.3\", features = [\"fmt\", \"env-filter\"] }}\n\
helio = {{ git = \"https://github.com/Far-Beyond-Pulsar/Helio\" }}\n\n\
[profile.dev]\n\
opt-level = {}\n\
debug = {}\n",
        package_lines.join("\n"),
        profile_opt,
        profile_debug
    );

    std::fs::write(&cargo_toml_path, cargo_content)
        .map_err(|e| format!("Failed to write Cargo.toml: {e}"))?;

    Ok(())
}

/// Ensure the core project bootstrap files exist and are up to date.
///
/// This is engine-owned project wiring. PBGC should only emit class files.
pub fn ensure_core_bootstrap(project_root: &Path) -> Result<(), String> {
    ensure_core_cargo_toml(project_root)?;

    let src_dir = project_root.join("src");
    std::fs::create_dir_all(&src_dir)
        .map_err(|e| format!("Failed to create src directory: {e}"))?;

    let classes_dir = src_dir.join("classes");
    std::fs::create_dir_all(&classes_dir)
        .map_err(|e| format!("Failed to create classes directory: {e}"))?;

    let classes_mod = classes_dir.join("mod.rs");
    if !classes_mod.exists() {
        std::fs::write(
            &classes_mod,
            "//! Generated by Pulsar Core Project Builder.\n",
        )
        .map_err(|e| format!("Failed to write classes/mod.rs: {e}"))?;
    }

    let main_rs = src_dir.join("main.rs");
    let should_write_main = if main_rs.exists() {
        let existing = std::fs::read_to_string(&main_rs)
            .map_err(|e| format!("Failed to read existing main.rs: {e}"))?;

        // Migrate previously generated stale bootstrap.
        existing.contains("generated by Pulsar Blueprint Compiler")
            || existing.contains("mod blueprints;")
    } else {
        true
    };

    if should_write_main {
        let project_name = project_root
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("pulsar_project");

        let main_content = format!(
            r#"//! {project_name} — generated by Pulsar Core Project Builder.

use pulsar_game::prelude::*;

mod classes;

fn main() {{
    tracing_subscriber::fmt()
        .with_env_filter(std::env::var("RUST_LOG").unwrap_or_else(|_| "info".into()))
        .init();

    tracing::info!("Starting {{}}", env!("CARGO_PKG_NAME"));

    let threads = std::thread::available_parallelism()
        .map(|n| n.get())
        .unwrap_or(4);

    let mut game = TickLoop::new(TickMode::default(), threads);

    tracing::info!("World ready — entering tick loop");
    game.run_blocking();
}}
"#
        );

        std::fs::write(&main_rs, main_content)
            .map_err(|e| format!("Failed to write src/main.rs: {e}"))?;
    }

    Ok(())
}
