//! Registered component values as owned, type-erased data.
//!
//! Every registered class supplies a default factory, a JSON boundary
//! decoder and a clone (generated by `#[register_world_component]`). The
//! owned value they produce is inserted with SceneDB's
//! [`World::insert_dyn`], which runs exactly the write hooks a typed
//! `World::insert` runs -- GPU mirror (including generated GPU companions),
//! handle ledger, change tracking, journals and subscriptions. Nothing here
//! is class-specific, and nothing re-derives GPU state by hand.

use std::any::Any;

use pulsar_scenedb::{ComponentId, Entity, InsertDynError, World};
use serde_json::Value;

/// Why an owned value could not be inserted. Each variant that rejects a
/// value hands it back.
#[derive(Debug, thiserror::Error)]
pub enum ComponentValueError {
    #[error("`{0}` is not a registered world component class")]
    UnknownClass(String),
    #[error("the value is not a `{class}`")]
    TypeMismatch {
        class: String,
        value: Box<dyn Any + Send + Sync>,
    },
    #[error("entity {entity} is not alive")]
    DeadEntity {
        entity: Entity,
        value: Box<dyn Any + Send + Sync>,
    },
}

/// A new default value of `class_name`. `None` if the class is not
/// registered here.
pub fn new_world_component_value(class_name: &str) -> Option<Box<dyn Any + Send + Sync>> {
    crate::find(class_name).map(|registration| (registration.default_value)())
}

/// Decode `class_name`'s value from JSON (a file or tool boundary). `None`
/// if the class is not registered here; `Some(Err)` if the JSON does not
/// decode as that class.
pub fn decode_world_component_value(
    class_name: &str,
    data: &Value,
) -> Option<Result<Box<dyn Any + Send + Sync>, String>> {
    crate::find(class_name).map(|registration| (registration.decode)(data))
}

/// A clone of `entity`'s live `class_name` value, or `None` if the class is
/// not registered or `entity` has no such value.
pub fn clone_world_component_value(
    class_name: &str,
    world: &World,
    entity: Entity,
) -> Option<Box<dyn Any + Send + Sync>> {
    let registration = crate::find(class_name)?;
    let value = world.get_dyn(entity, (registration.component_type)())?;
    (registration.clone_value)(value)
}

/// Insert an owned `class_name` value on `entity`, replacing any value of
/// that class already there, through SceneDB's erased insert. The value's
/// concrete type is checked against the class before anything is written.
pub fn insert_world_component_value(
    class_name: &str,
    world: &mut World,
    entity: Entity,
    value: Box<dyn Any + Send + Sync>,
) -> Result<ComponentId, ComponentValueError> {
    let Some(registration) = crate::find(class_name) else {
        return Err(ComponentValueError::UnknownClass(class_name.to_string()));
    };
    let expected = (registration.register_erased)();
    if pulsar_scenedb::component::try_resolve_id((*value).type_id()) != Some(expected) {
        return Err(ComponentValueError::TypeMismatch {
            class: class_name.to_string(),
            value,
        });
    }
    world
        .insert_dyn(entity, value)
        .map_err(|error| match error {
            InsertDynError::DeadEntity { entity, value } => {
                ComponentValueError::DeadEntity { entity, value }
            }
            // `register_erased` ran above, so the type is registered.
            InsertDynError::Unregistered { .. } => {
                unreachable!("`{class_name}` was registered for erased insertion just above")
            }
        })
}

/// Set one reflected property on `entity`'s live `class_name` value, then
/// let the class re-establish whatever it derives from that property, all
/// under one SceneDB write guard: subscribers, journals and the GPU mirror
/// observe a single write carrying the final value.
///
/// Hands `value` back if the class, the value or the property does not
/// exist.
pub fn set_world_component_property(
    class_name: &str,
    world: &mut World,
    entity: Entity,
    property: &str,
    value: Box<dyn Any>,
) -> Result<(), Box<dyn Any>> {
    let Some(registration) = crate::find(class_name) else {
        return Err(value);
    };
    let Some(mut instance) = (registration.get_as_engine_class_mut)(world, entity) else {
        return Err(value);
    };
    let Some(metadata) = instance
        .get_properties()
        .into_iter()
        .find(|candidate| candidate.name == property)
    else {
        return Err(value);
    };
    (metadata.setter)(&mut *instance, value);
    (registration.property_written)(&mut *instance, Some(property));
    Ok(())
}

/// Generic implementations of a registration's erased operations, for
/// hand-written [`crate::WorldComponentRegistration`]s (the macro generates
/// the same).
pub mod erased {
    use std::any::Any;

    use pulsar_reflection::EngineClass;
    use serde_json::Value;

    /// `default_value` for `T`.
    pub fn default_value<T: Default + Any + Send + Sync>() -> Box<dyn Any + Send + Sync> {
        Box::new(T::default())
    }

    /// `decode` for a `T` whose JSON boundary form is its serde form.
    pub fn decode_json<T: serde::de::DeserializeOwned + Any + Send + Sync>(
        data: &Value,
    ) -> Result<Box<dyn Any + Send + Sync>, String> {
        serde_json::from_value::<T>(data.clone())
            .map(|value| Box::new(value) as Box<dyn Any + Send + Sync>)
            .map_err(|error| error.to_string())
    }

    /// `clone_value` for `T`.
    pub fn clone_value<T: Clone + Any + Send + Sync>(
        value: &dyn Any,
    ) -> Option<Box<dyn Any + Send + Sync>> {
        value
            .downcast_ref::<T>()
            .map(|value| Box::new(value.clone()) as Box<dyn Any + Send + Sync>)
    }

    /// `property_written` for a class that derives nothing from its fields.
    pub fn no_property_written(_value: &mut dyn EngineClass, _property: Option<&str>) {}
}
