use serde::{Deserialize, Serialize};

use crate::error::PluginError;
use crate::JsonValue;

// ============================================================================
// AI Tools Support
// ============================================================================

/// Definition of an AI-accessible tool provided by a plugin.
///
/// Tools are generated by the `#[ai_tool]` proc macro, which creates:
/// - A tool definition with JSON schema for parameters
/// - A wrapper function for JSON-based parameter dispatch
/// - A documentation constant with embedded markdown
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AiToolDefinition {
    /// Unique tool name (snake_case)
    pub name: String,

    /// Human-readable description of the tool
    pub description: String,

    /// JSON schema for input parameters (property definitions)
    /// Format: `{"type": "object", "properties": {...}, "required": [...]}`
    pub parameters_json_schema: JsonValue,

    /// Tool category for organization (e.g., "refactoring", "validation")
    pub category: Option<String>,
}

impl AiToolDefinition {
    /// Create a new AI tool definition
    pub fn new(
        name: impl Into<String>,
        description: impl Into<String>,
        parameters_json_schema: JsonValue,
    ) -> Self {
        Self {
            name: name.into(),
            description: description.into(),
            parameters_json_schema,
            category: None,
        }
    }

    /// Add a category to this tool definition
    pub fn with_category(mut self, category: impl Into<String>) -> Self {
        self.category = Some(category.into());
        self
    }
}

/// Filesystem context for AI tools
///
/// Provides controlled access to files and directories, ensuring tools
/// can safely interact with the filesystem without compromising security.
#[derive(Debug, Clone)]
pub struct FsContext {
    /// Root directory that tools are allowed to access
    pub allowed_root: std::path::PathBuf,

    /// Whether tools can create new files
    pub allow_create: bool,

    /// Whether tools can modify existing files
    pub allow_modify: bool,

    /// Whether tools can delete files
    pub allow_delete: bool,

    /// List of file extensions tools are allowed to access
    pub allowed_extensions: Vec<String>,
}

impl FsContext {
    /// Create a context allowing all filesystem operations in a directory
    pub fn unrestricted(root: std::path::PathBuf) -> Self {
        Self {
            allowed_root: root,
            allow_create: true,
            allow_modify: true,
            allow_delete: true,
            allowed_extensions: vec![],
        }
    }

    /// Create a read-only context
    pub fn read_only(root: std::path::PathBuf) -> Self {
        Self {
            allowed_root: root,
            allow_create: false,
            allow_modify: false,
            allow_delete: false,
            allowed_extensions: vec![],
        }
    }

    /// Restrict to specific file extensions
    pub fn with_extensions(mut self, extensions: Vec<String>) -> Self {
        self.allowed_extensions = extensions;
        self
    }

    /// Check if a path is allowed
    pub fn is_allowed(&self, path: &std::path::Path) -> bool {
        if !path.starts_with(&self.allowed_root) {
            return false;
        }

        if !self.allowed_extensions.is_empty() {
            if let Some(ext) = path.extension() {
                if let Some(ext_str) = ext.to_str() {
                    return self.allowed_extensions.iter().any(|e| e == ext_str);
                }
            }
            return false;
        }

        true
    }
}

// ============================================================================
// AI Tools Extension Trait
// ============================================================================

/// Optional trait for plugins that provide AI-accessible tools.
///
/// Implement this on your [`EditorPlugin`](crate::plugin::EditorPlugin) type
/// to expose custom AI tools that can be invoked by the AI assistant.
pub trait EditorPluginAi: crate::plugin::EditorPlugin {
    /// Get AI-accessible tools provided by this plugin.
    fn ai_tools(&self) -> Vec<AiToolDefinition> {
        Vec::new()
    }

    /// Execute an AI tool provided by this plugin.
    fn execute_ai_tool(
        &self,
        file_path: &std::path::Path,
        tool_name: &str,
        tool_args: JsonValue,
    ) -> Result<JsonValue, PluginError> {
        let _ = (file_path, tool_name, tool_args);
        Err(PluginError::Other {
            message: "Tool execution not supported by this plugin".to_string(),
        })
    }

    /// Get capabilities for a specific file.
    fn capabilities_for_file(&self, file_path: &std::path::Path) -> Vec<String> {
        let _ = file_path;
        Vec::new()
    }
}
