//! The Rust-export drift probe (#652): an actor generated by
//! `pulsar_script_codegen` (see `build.rs`), compiled against the pinned
//! `pulsar_scenedb::Actor` and driven through the real tick loop.

#![cfg(test)]

mod generated {
    // The generated file is an `events.rs`: it names this crate as
    // `pulsar_game` and may leave helpers unused.
    #![allow(dead_code, unused_imports)]
    include!(concat!(env!("OUT_DIR"), "/export_probe_actor.rs"));
}

use crate::blueprint_codegen_drift::{REFERENCE_BEGIN_PLAY_SIGNATURE, REFERENCE_TICK_SIGNATURE};

const SOURCE: &str = include_str!(concat!(env!("OUT_DIR"), "/export_probe_actor.rs"));

/// THE drift assertion (#652): the emitted `impl Actor` signatures must be
/// byte-identical to the reference twin compiled against the pinned trait,
/// and the emission may not name any crate the pinned graph does not
/// provide. (That it compiles at all, above, is the stronger half.)
#[test]
fn emitted_actor_signatures_match_the_pinned_actor_trait() {
    assert!(
        SOURCE.contains(REFERENCE_TICK_SIGNATURE),
        "the emitted Actor::tick drifted from the pinned time-free trait (expected `{REFERENCE_TICK_SIGNATURE}`)"
    );
    assert!(
        SOURCE.contains(REFERENCE_BEGIN_PLAY_SIGNATURE),
        "the emitted Actor::begin_play drifted from the pinned trait"
    );
    assert!(
        !SOURCE.contains("GameTime"),
        "`Actor::tick` is time-free at the pin; no GameTime may be emitted"
    );
    assert!(
        !SOURCE.contains("gamma_core"),
        "emitted code names `gamma_core`, which the pinned graph does not provide"
    );
}

/// The generated actor runs on the real tick loop: a waiting `begin_play`
/// resumes on a later tick and `tick` runs once per tick, per actor.
#[test]
fn the_generated_actor_registers_and_ticks_through_the_real_tick_loop() {
    use crate::prelude::*;

    let mut game = crate::tick::TickLoop::new(pulsar_core::TickMode::default(), 0);
    {
        let mut store = game.scene_store.write();
        game.actors
            .register(generated::ExportProbe::new(), &mut store.world);
        game.actors
            .register(generated::ExportProbe::new(), &mut store.world);
    }
    for _ in 0..3 {
        game.tick_once();
    }
}

#[test]
fn a_clone_is_a_fresh_actor() {
    let actor = generated::ExportProbe::new();
    let _clone = actor.clone();
}
