//! # pulsar_game
//!
//! The Pulsar game runtime crate.  Provides:
//!
//! - **Archetypal ECS** — `World`, `Entity`, `Component`, queries.
//! - **Actor lifecycle** — `Actor` trait with `begin_play` / `end_play` / `tick`.
//! - **System schedule** — ordered `Schedule` of ECS `SystemFn`s.
//! - **Tick loop** — `TickLoop` with fixed or variable timestep.
//! - **Async task pool** — smol-backed `TaskPool` for background work.
//! - **Event channels** — `EventWriter<T>` / `EventReader<T>`.
//! - **Game time** — `GameTime` and `DeltaTime`.

pub use pulsar_core::{EventBuffer, EventReader, EventWriter, GameTime, TaskPool, TickMode};
// Generated actors address the live world through `pulsar_world_registry`'s
// dispatcher.
pub use pulsar_scenedb::{
    Actor, ActorRegistry, Archetype, ArchetypeId, ArchetypeKey, Component, Entity, QueryIter,
    Schedule, World, WorldQuery,
};

// Script classes on the engine script VM (module.json builds).
pub mod scripting;

// Window / rendering integration
pub mod camera_selection;
pub mod freecam;
pub mod window;
pub mod windowed_app;

// Play In Editor — host-driven embedding (issue #243)
pub mod embed;

// Standalone entry point: content discovery, headless runs (#926)
pub mod standalone;

// Legacy tick loop (uses extracted primitives)
pub mod tick;

// The one pulsar_core::GameTime <-> pulsar_scenedb::GameTime seam (#652)
pub mod time;

// Gameplay script-crate actors: identity-tagged registration + native hot
// reload (#653). Generated projects and scripts/ crates register through
// `TickLoop::register_actor`.
pub mod scripts;

// Cross-object reference resolution for blueprint graphs (#654): the one
// implementation BOTH compile targets call (VM trampolines + generated Rust).
pub mod script_refs;

/// Component vocabulary gameplay scripts attach most often (#653).
///
/// User script crates depend only on `pulsar_game`; this module is their
/// single import surface for making entities visible — a mesh plus its
/// placement. Re-exports, not wrappers: these are the SAME types the
/// renderer's maintainers subscribe to, so mutations made through them are
/// visible on the next frame exactly like editor edits.
pub mod scene {
    pub use engine_backend::scene::{Name, Transform, Visibility};
    pub use helio_component::components::{LightComponent, MeshAssetPath, StaticMeshComponent};
    /// Components attach to objects as instance entities (Pulsar-Native#1035):
    /// `attach_value` adds one, `attachments` finds and edits them.
    pub use pulsar_world_registry::pulsar_scene_model::attachments;
    pub use pulsar_world_registry::{attach_value, AttachError};
}

// Exported (generated) actors name this crate as `pulsar_game`; inside it,
// that path is this crate.
extern crate self as pulsar_game;

// Compile-time drift guard: exported actors must match the pinned crates
#[cfg(test)]
mod blueprint_codegen_drift;

// The always-compiled probe: an actor generated by `build.rs`
#[cfg(test)]
mod export_probe;

#[cfg(test)]
mod tests;

#[cfg(test)]
mod test_probe;

/// Convenience prelude — glob-import this to get the whole public API.
pub mod prelude {
    pub use crate::{
        freecam::FreeCam,
        scripting::ScriptRuntime,
        tick::{ScriptStats, SharedTickLoop, TickLoop},
        window::{RenderCamera, WindowDescriptor, WindowHandle, WindowManager},
    };
    pub use pulsar_core::{EventReader, EventWriter, GameTime, TaskPool, TickMode};
    pub use pulsar_scenedb::{
        Actor, ActorRegistry, Component, Entity, QueryIter, Schedule, World, WorldQuery,
    };
}
